- src/DataDictionary/DataDictionaryNode.js
- src/Explorer/ExplorerTable.jsx
- src/Explorer/style.js
- src/components/CheckBox.jsx
r @frickjack @philloooo 
Make the list of choices (projects, file types, file formats) collapsible
#161
> feat(collapsed): reduce displayed list

- src/Submission/ReduxProjectSubmission.js
not custom_headers
This bug breaks tsv submissions in the data-portal.  Doh!
> fix(ReduxProjectSubmission): customHeaders

- src/DataDictionary/DataDictionaryNode.jsx
- src/DataDictionary/DataDictionaryNode.test.jsx
- src/DataDictionary/GraphCreator.js
- src/actions.js
> fix(Dictionary): tolerate , in enum props

- src/Popup/Popup.jsx
- src/Popup/SavePopup.jsx
- src/Popup/__snapshots__/Popup.test.jsx.snap
- src/Submission/SubmitForm.jsx
- src/UserProfile/ReduxUserProfile.js
- src/UserProfile/ReduxUserProfile.test.jsx
- src/UserProfile/UserProfile.jsx
- src/UserProfile/UserProfile.test.jsx
- src/UserProfile/reducers.js
- src/components/CheckBox.jsx
[related pr in fence](https://github.com/uc-cdis/fence/pull/61)
Change UserPorfile page to help users manage list of refresh tokens
r @philloooo @frickjack
> feat(jti): listing refresh token

- src/Popup/SavePopup.jsx
- src/UserProfile/ReduxUserProfile.test.jsx
- src/UserProfile/UserProfile.jsx
- src/UserProfile/UserProfile.test.jsx
- follow https://github.com/uc-cdis/data-portal/issues/192, rename saved file name to `credentials.json`
- remove the utf-8 encode which adds a BOM header to the json file that's not recognized by python json loader
- rename refresh token to API key, token id to key id
> fix(label): change label and key

- data/getSchema.js
> chore(hostname): adapt to openstack

- data/getSchema.js
> fix(hostname): internal useage for openstack

- src/UserProfile/ReduxUserProfile.js
has to go together with https://github.com/uc-cdis/fence/pull/70
> fix(scope): scopes -> scope for oauth2 spec

- Jenkinsfile
- data/getSchema.js
fetching dictionary via http://revproxy requires
using http agent - https agent bombs
> fix(getSchema): use http agent for http://revproxy

- nginx.conf
fix paths like /data that actually exist on
the file system, and were getting redirected
erroneously
> fix(nginx): confused by paths like /data

- src/Login/Login.jsx
- src/Login/Login.test.jsx
- src/Login/ProtectedContent.jsx
- src/Login/ReduxLogin.js
- src/Login/reducers.js
- src/index.jsx
- src/localconf.js
- src/reducers.js
r @frickjack 
Multiple login ticket
> feat(multiple): multiple login

- custom/graphql/kf-gql.njk
- src/Login/Login.jsx
- src/Login/ProtectedContent.jsx
- src/localconf.js
> feat(dict): new dictionary

- custom/graphql/genomel-gql.njk
- src/Homepage/Redux/ParamProjectDashboard.jsx
- src/Homepage/Redux/ProjectTable.jsx
- src/localconf.js
> fix(genomel): homepage

- src/Login/ProtectedContent.jsx
handle 401 case
this is the only place that we check 403 and it's supposed to be deprecated
> fix(code): check for 401 too

- src/UserProfile/ReduxUserProfile.js
- src/UserProfile/ReduxUserProfile.test.jsx
resolve #224 
@thanh-nguyen-dang
> fix(ErrMessage): fix error message when deleting key

- src/localconf.js
> chore(ndh): add workspace nav

- src/Explorer/ExplorerTable.jsx
- src/Popup/Popup.jsx
- src/Popup/__snapshots__/Popup.test.jsx.snap
> feat(expires): Add expires_in for data links

- data/parameters.js
- src/components/Introduction.jsx
> feat(nc): new commons support

- .eslintrc.js
- .gitignore
- .travis.yml
- Dockerfile
- data/getTexts.js
- data/parameters.js
- dockerStart.sh
- package.json
- src/DataModelGraph/ReduxDataModelGraph.js
- src/Homepage/reduxer.js
- src/Index/page.jsx
- src/Index/reduxer.jsx
- src/Login/Login.test.jsx
- src/Login/ProtectedContent.jsx
- src/Login/ProtectedContent.test.jsx
- src/Login/ReduxLogin.js
- src/Top/reduxer.js
- src/components/GoogleAnalytics.jsx
- src/index.jsx
- src/localconf.js
- testSchema.sh
- webpack.config.js
> feat(ga): add google analytics

- src/css/base.less
> fix(css): set font on body so we don't break ace-editor

- data/parameters.js
> chore(acct): add graphql for acct

- data/parameters.js
- testSchema.sh
@frickjack @zflamig @fortuno 
new numbers to display in homepage of NIAID and KidsFirst according to Francisco
> feat(new-number): change to new numbers in kf ndh

- .storybook/config.js
- .storybook/preview-head.html
- .storybook/webpack.config.js
- src/stories/buttons.jsx
- src/stories/charts.jsx
- src/stories/index.jsx
Fixing the missing styles on Storybook - added a few more loaders to the Webpack config, added in our stylesheet, and added some of our already existing components + broke them up into separate files. I think we should follow this structure (or something like it) going forward with Storybook stories.
> PXD-1087 fixed Storybook styling

- src/components/layout/TopIconButton.jsx
- src/components/layout/TopIconButton.less
- testSchema.sh
> fix(btn-text-color): remove styled component and move to less

- .stylelintrc.js
- .travis.yml
- package-lock.json
- package.json
- src/Analysis/Analysis.less
- src/Arranger/AggregationTabs.test.jsx
- src/Certificate/Question.less
- src/CoreMetadata/page.jsx
- src/DataDictionary/DataDictionary.less
- src/DataDictionary/DictionaryGraph.test.jsx
- src/DataExplorer/DataExplorer.less
- src/Explorer/ExplorerTable.less
- src/GraphQLEditor/GqlEditor.less
- src/Login/Login.test.jsx
- src/components/cards/DataSummaryCardGroup.less
- src/components/charts/SummaryChartGroup.less
- src/components/filters/FilterGroup/FilterGroup.less
- src/components/filters/RangeFilter/RangeFilter.less
- src/components/filters/RangeFilter/RangeFilter.test.jsx
- src/components/filters/SingleSelectFilter/SingleSelectFilter.less
- src/components/layout/TopIconButton.less
- src/components/tables/DataExplorerTable/DataExplorerTable.less
(Will pass once PXD-1315 is merged in)
Imported stylelint to take care of CSS linting - plan is to turn off ESLint and any CSS/Less linting on Codacy since they conflict sometimes.
Stylelint also cleaned up some of our code.
> PXD-1316 Stylelint

- LICENSE
- NOTICE
> feat(NOTICE): update LICENSE and NOTICE

- src/DataExplorer/DataExplorer.less
- src/components/cards/CountBox.less
- src/components/charts/SummaryHorizontalBarChart/SummaryHorizontalBarChart.less
- src/components/charts/SummaryHorizontalBarChart/index.jsx
- src/components/charts/SummaryPieChart/SummaryPieChart.less
- src/components/charts/SummaryPieChart/index.jsx
- src/components/tables/DataExplorerTable/DataExplorerTable.less
Small style tweaks to align more closely with spec.
> PXD-1364 Match explorer to spec

- src/components/charts/IndexBarChart/index.jsx
- src/components/charts/PercentageStackedBarChart/index.jsx
- src/components/charts/SummaryChartGroup/index.jsx
- src/components/charts/SummaryHorizontalBarChart/index.jsx
- src/components/charts/SummaryPieChart/index.jsx
Replaced hardcoded styles in charts w/ props to make them more configurable in case we have other uses for them later.
> PXD-1521 Make charts customizable

- .storybook/webpack.config.js
- Dockerfile
- data/parameters.js
- package.json
- src/DataExplorer/DataExplorerVisualizations.test.jsx
- src/components/charts/helper.js
- src/components/charts/helper.test.js
- webpack.config.js
Added default environment vars and the arranger config need for brain commons. Also fixed the issue where the code defaulted to "subject" as the index.
> PXD-1693 Default ENV vars, BHC params

- src/components/charts/SummaryHorizontalBarChart/SummaryHorizontalBarChart.less
- src/components/charts/SummaryHorizontalBarChart/index.jsx
- src/components/charts/SummaryPieChart/SummaryPieChart.less
- src/components/charts/SummaryPieChart/index.jsx
Rewrite legend in div tags instead of SVG lements, in order to apply CSS
> PXD-1839 fix(overlap): fix chart text overlap bug

- data/config/gtex.json
- package-lock.json
- package.json
- src/DataExplorer/DataExplorer.less
- src/DataExplorer/DataExplorerVisualizations.jsx
- src/DataExplorer/custom/bdbag.js
- src/DataExplorer/utils.js
- src/components/tables/DataExplorerTable/DataExplorerTable.less
Usage: in `parameters.js`, enable more than one buttons pointing at same `dropdownId`
> PXD-1869 fix(dropdown): import dropdown button

- src/DataExplorer/utils.js
A bug that won't download when fetching 0 records
> fix(keycheck): key check for 0 should return true

- src/index.less
Add min height for main content (forgot in my last PR 🤦‍♀️
> fix(height): add min height for main content

- Jenkinsfile
> fix(jenkins): remove outdated pipeline

- src/Arranger/ArrangerWrapper.jsx
> fix(arranger): wrapper filter edge case

- src/Submission/MapFiles.jsx
- src/Submission/reducers.js
- src/Submission/utils.js
- src/components/tables/TransactionLogTable.jsx
In data dictionary table, hide if the property is system property
In data dictionary table, hide if the property is system property
> fix(system-property): hide system properties

- src/Layout/reduxer.js
The portal version wasn't being display in the footer - small fix to change the prop name.
- Prop for portal version incorrectly named
> PXP-2164 Fix portal version

- data/config/gtex.json
Need to add tooltip to the download clinical data button as well in STAGE.
- Tooltip for Download Clinical button
> add tooltip to other button

- src/DataDictionary/table/DataDictionaryPropertyTable/index.jsx
Add term for properties in data dictionary table
> fix(term): add property term in data dictionary table

- data/config/bpa.json
- data/config/dcf.json
- data/config/default.json
Changing link on top bar to say "Submit Data" to be consistent with the rest of Windmill.
> PXP-2259 Change link on top bar

- src/Submission/MapFiles.jsx
Orders unmapped files by date, starting with the most recently uploaded files.
- Files were unordered before
> PXP-2260 order unmapped files by date descending

- data/gqlHelper.js.njk
- src/DataDictionary/table/DataDictionaryPropertyTable/index.jsx
- src/Explorer/ExplorerTable.jsx
- src/Submission/MapDataModel.jsx
- src/Submission/MapFiles.jsx
- src/Submission/SubmissionHeader.jsx
- src/Submission/utils.js
- src/components/tables/TransactionLogTable.jsx
- src/utils.js
Fixes typo in querying core_metadata_collection node
- Typo in query
> fix query typo

- src/QueryNode/QueryForm.jsx
- src/QueryNode/QueryNode.jsx
- src/QueryNode/QueryNode.less
Added a "download all" button to our query page so a user can download all tsvs for a given node in a program/project.
> download tsv button

- src/Submission/MapDataModel.jsx
Removes the required property "type" since the user already fills out this information.
> filter out type

- src/Submission/MapFiles.jsx
Makes sure that files are sorted by date and still can select all.
- Select all was broken due to the grouping not being by date.
> fix select all

- src/Submission/MapDataModel.jsx
- src/Submission/MapFiles.jsx
- src/Submission/MapFiles.less
This disables the submit button once a user has clicked it so that they can't submit twice. It also makes the error message persistent instead of fading out.
- Permanent (until close button is clicked) error message after submit
- Lock submit button once clicked
> Data upload fixes

- src/Submission/MapDataModel.jsx
There was a bug with data upload validation - the submit button should only appear if all required fields are filled out, and when a user removes text the value is an empty string. The validation was only checking for null so it considered this a valid input.
- Validation bug - check for empty strings and null
> PXP-2290 fix data upload validation bug

- data/config/bpa.json
- data/config/gtex.json
- src/UserAgreement/Question.jsx
- src/UserAgreement/Quiz.jsx
- certificate quiz with one question, and one answer for that question
- eliminate the number before every question when there is only one question
> feat(bpa-cert): certificate for bpa

- data/config/ncrdc-demo.json
Workspace button in DCF Sandbox
> feat(demo): Add workspace button to sandbox

- src/index.jsx
- src/localconf.js
add error url for workspace access error
> fix(workspace): add error url for workspace

- src/Workspace/Workspace.less
added min-height: inherit to workspace; firefox doesn't understand webkit values
> Workspace Height Firefox Bug

- data/config/anvil.json
- data/config/bhc.json
- data/config/default.json
- data/config/gtex.json
- data/config/kfDcfInterop.json
- data/config/ncrdc-demo.json
- data/config/ndh.json
- src/Arranger/ArrangerWrapper.jsx
- src/DataExplorer/DataExplorer.less
- src/DataExplorer/DataExplorerFilters.jsx
- src/DataExplorer/DataExplorerFilters.test.jsx
- src/DataExplorer/DataExplorerVisualizations.jsx
- src/DataExplorer/DataExplorerVisualizations.test.jsx
- src/DataExplorer/actionHelper.js
- src/DataExplorer/arrangerQueryHelper.js
- src/DataExplorer/custom/bdbag.js
- src/DataExplorer/index.jsx
- src/DataExplorer/utils.js
- src/GraphQLEditor/GqlEditor.jsx
- src/components/charts/helper.js
- src/components/charts/helper.test.js
- src/components/tables/DataExplorerTable/DataExplorerTable.less
- src/components/tables/DataExplorerTable/index.jsx
- Removes the checkboxes from the Arranger table
- Reorganizes configuration to show diff between explorer and arranger config
- Added configuration to hide table per commons
- Need to update gitops config before rolling
- User can select all now! 🎉
> PXP-2495 Feat/remove checkboxes

- data/config/gtex.json
- src/DataExplorer/DataExplorerVisualizations.jsx
This implements the configuration to allow STAGE to have the homepage give an aggregated overview of datasets.
- Tiered access for STAGE homepage
> Tiered Access for STAGE

- data/config/ndh.json
add 4 facets to ndh explorer filter
- add 4 more facets to ndh explorer filter
> fix(ndh): add facets to ndh explorer

- data/config/genomel.json
> Add workspace tab

- data/config/genomel.json
Remove link to /shiny. No ETL for this commons.
> Remove "Explore Data", changed description

- data/config/bhc.json
Changes local configuration to be "BRAIN" vs. "Brain"
- Updated Brain to be acronym
> Fix BRAIN typos

- data/config/gtex.json
- data/config/kfDcfInterop.json
Changed configuration in KF and STAGE to show "DataSTAGE" as one word.
- DataSTAGE branding
> DataSTAGE is one word

- data/config/gtex.json
Removes the title on the homepage for STAGE since it's already in the logo
- UI looks cleaner
> Remove title for STAGE

- webpack.config.js
- enable source map tool so that developers could have better debugging under dev mode
> fix(srcmap): add source map for better debugging under dev mode

- src/Submission/SubmissionResult.jsx
- src/Submission/SubmissionResult.test.jsx
- src/Submission/reducers.js
- fix the error filter to get right error entities for submission result
- make submission status shows the overall status
> chore(chunk): show overal status

- data/config/va.json
Adds facets to Mickey that are more relevant and useful than current ones.
- More relevant Explorer.
> New Micket facets

- src/DataExplorer/DataExplorer.less
- src/Login/Login.less
- src/components/charts/SummaryChartGroup/SummaryChartGroup.less
Makes charts even width and not overflow in explorer, no overflow in facet texts, and puts buttons on login page in column flow
- Makes charts even width and not overflow in explorer, no overflow in facet texts, and puts buttons on login page in column flow
> Explorer and login page UI fixes

- data/config/va.json
- src/DataExplorer/actionHelper.js
- src/DataExplorer/arrangerQueryHelper.js
- src/DataExplorer/arrangerQueryHelper.test.js
> feat(export): allow fetch by bucket

- package.json
- runWebpack.sh
- sanity-check.js
Before starting the server, let's check if the homepage chart config in portal config is correct. 
- Before starting, check if the homepage chart config in portal config is correct
> feat(sanity-check): check portal config works for homepage charts

- src/GuppyDataExplorer/GuppyDataExplorer.css
- src/Submission/ProjectSubmission.jsx
- src/Submission/ProjectSubmission.less
Just some CSS: Add tiny paddings for guppy explorer, and ProjectSubmission page
> fix(padding): add tiny paddings for guppy explorer

- src/Submission/ProjectSubmission.less
- src/Workspace/Workspace.less
- Fixes some padding inconsistencies for the responsive layout
> Fix padding in Workspace and Submit Data page

- src/DataExplorer/arrangerQueryHelper.test.js
- src/Submission/MapDataModel.jsx
- src/Submission/MapDataModel.less
- src/Submission/reducers.js
- src/components/StickyToolbar.less
- For the data upload process, we were casting everything to a string. This created issues when the required input was a number. Fixes to parse as an when needed integer. 
- Also fixes UI bug with the floating table header on the Data Upload page
> Fix Integer casting for Data Upload

- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
I believe this PR will fix the original bug that Sean reported.
> fix: guppy explorer using incorrect manifest format

- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- Fix for issue where Guppy's downloadRawDataByTypeAndFilter() is returning different data formats in different commons.
> chore: adapt manifest format to indices

- src/components/layout/Footer.jsx
- src/index.jsx
- Fix errors when privacy policy is not set up
> fix(privacy-policy)

- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- On export to workspace, exported all files associated with the cases in the cohort, even if file type was filtered
- Now a user will only send files of the type of interest to the workspace
> If file format facet selected, filter exported files by that

- src/UserAgreement/Question.jsx
- src/UserAgreement/Question.less
- allow line break in quiz/policy page
> chore(policy): allow line break

- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- Implemented new `sower` requests with specifying action type
- New `sower` requests.
This change requires `sower` version >= `0.3.0`.
> PXP-3754: "action" field for sower

- docs/data_availability_tool.md
- src/GuppyDataExplorer/ExplorerHeatMap/index.jsx
- DAT: do not automatically capitalize field names when a mapping is provided
- DAT: add "subject_id" to the configurable field name mapping
- DAT: show X axis values when the field is not numeric
> DAT improvements

- data/config/gtex.json
- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- src/GuppyDataExplorer/index.jsx
- Utilizes the PFB job to export to Terra instead of BDBag
- Requires a url to be specified in `dataExplorerConfig` called `terraExportURL`
- This should be `bvdp-saturn-${env}.appspot.com/#import-data`, where `${env}` is `dev`, `staging`, or `prod`
> Export to Terra using PFB

- src/Login/Login.jsx
- add desc and secondary to login buttons
> add desc and secondary to login buttons

- src/Login/Login.jsx
Fix console warnings
- Invalid prop `buttonType` of value `` supplied to `Button`, expected one of ["primary","secondary","default"]
- Each child in a list should have a unique "key" prop.
> fix(warnings)

- src/CoreMetadata/CoreMetadataHeader.jsx
- src/components/FileTypePicture.jsx
Reverts uc-cdis/data-portal#582
> Revert "fix/default file type"

- src/HIVCohortFilter/ECCase.jsx
- src/HIVCohortFilter/LTNPCase.jsx
simply put this block in portal config to customize which projects to included for ndh HIV app 
```
"hivAppProjects": [
"HIV-CHARLIE"
]
```
By default it will be ["HIV-CHARLIE"] if not set
- customizable project lists for ndh hiv app
> fix(project): customizable project lists for hiv app

- src/components/tables/ProjectTable.less
PXP-4448
Give submit data button min and max widths
> PXP-4448 fix(button-css): button width to px

- package-lock.json
- package.json
- src/QueryNode/QueryNode.jsx
- src/Submission/ProjectSubmission.jsx
- src/Submission/SubmissionHeader.jsx
- src/authMappingUtils.js
- src/components/Introduction.jsx
- src/components/layout/TopBar.jsx
- src/components/tables/ProjectTable.jsx
- src/components/tables/TransactionLogTable.jsx
- src/components/tables/reduxer.js
- src/reducers.js
Newer ui version fix a bug in chart that doesn't calculating percentage correctly. This PR also includes some lint fix. 
- update ui library version
> fix(version): update ui version

- src/HIVCohortFilter/ECCase.jsx
- src/HIVCohortFilter/HIVCohortFilterCase.jsx
- src/HIVCohortFilter/LTNPCase.jsx
- src/HIVCohortFilter/PTCCase.jsx
- src/HIVCohortFilter/__test__/ECCase-validate-results.js
- src/HIVCohortFilter/__test__/LTNPCase-validate-results.js
- src/HIVCohortFilter/__test__/PTCCase-validate-results.js
- src/localconf.js
- Fix HIV app by changing "follow_up" to "visit" according to dictionary update
> fix(hiv): change follow_up to visit

- src/HIVCohortFilter/ECCase.jsx
- src/HIVCohortFilter/HIVCohortFilterCase.jsx
- src/HIVCohortFilter/LTNPCase.jsx
- src/HIVCohortFilter/PTCCase.jsx
- improve HIV App's output according to Yilin's branch
> fix(app): improve output according to Yilin's branch

- package-lock.json
- package.json
- src/components/IndexButtonBar.css
- Fix homepage button fullwidth bug in Edge
> fix(edge): some bugfix and ui improvement for Windows Edge browser 

- src/HIVCohortFilter/LTNPCase.jsx
- src/HIVCohortFilter/PTCCase.jsx
- add more info to HIV app output
> fix(hiv): more fix to hiv app

- Dockerfile
- package-lock.json
- package.json
- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- src/GuppyDataExplorer/ExplorerVisualization/index.jsx
Jira: https://ctds-planx.atlassian.net/browse/PXP-4707?
Adds 'pending' state to buttons in Explorer when requests to Guppy are in flight.
Uses a combination of props passed from guppy and internal state in ExplorerButtonGroup to determine whether a request is in flight that will enable or disable the explorer's export / download buttons.
- Adds 'pending' state to buttons in Explorer when requests to Guppy are in flight.
> (PXP-4707) Add pending state to explorer buttons

- src/GuppyDataExplorer/ExplorerTable/index.jsx
- src/Submission/SubmitTSV.test.jsx
Resolves https://ctds-planx.atlassian.net/browse/PXP-4039
Deployed in https://qa-dcp.planx-pla.net/explorer
- Improves explorer table text caption
> fix: improve explorer table result number caption

- src/Submission/SubmitTSV.jsx
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-5053
- Fixed a bug that is causing submission page to crash due to a wrongly named property
> PXP-5053 fix/missing property

- README.md
- fix a typo in readme about homepage chart config
> fix(readme): fix a typo in readme about homepage chart config

- README.md
- Remove some unnecessary instructions in README
> fix(README): remove unnecessary run-schema part to avoid missleading

- docs/data_availability_tool.md
- src/GuppyDataExplorer/ExplorerVisualization/index.jsx
- Fix issue getting data for the DAT when the configured "caseField" is not "node_id"
> DAT fix: use caseField from config

- docs/resource_browser.md
- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- src/ResourceBrowser/Resource.jsx
- src/ResourceBrowser/ResourceBrowser.css
- src/ResourceBrowser/index.jsx
- src/components/layout/NavButton.less
- src/index.jsx
- src/localconf.js
Deployed at https://pauline.planx-pla.net and https://qa-covid19.planx-pla.net
Example config:
```
{
"components": {
"navigation": {
"items": [
{
"name": "Notebooks",
"link": "/resource-browser",
"icon": "query",
"color": "#a2a2a2"
}
]
}
},
"resourceBrowser": {
"title": "My Data Commons' Jupyter Notebooks",
"public": true,
"resources": [
{
"title": "Custom Notebook",
"category": "Notebooks",
"description": "This is a custom notebook that generates a bunch of charts",
"link": "https://pauline.planx-pla.net/dashboard/Public/notebooks/nb.html",
"imageUrl": "https://link-to-image.png"
},
{
"title": "Custom Notebook 2",
"link": "/dashboard/Public/notebooks/nb.html",
"imageUrl": "/relative-link-to-image.png"
}
]
}
}
```
more details in the docs
- Add resource browser
> Resource browser

- src/Login/Login.jsx
- src/Login/ProtectedContent.jsx
- src/Popup/ReduxAuthTimeoutPopup.jsx
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-5884
Portal now can redirects users back to the page they were from after login
Deployed at https://mingfei.planx-pla.net/
Try with: https://mingfei.planx-pla.net/files/2d5de954-5798-4b0c-88cb-e72ca2d3539e
- Fixed a bug causing incorrect redirects after login
> PXP-5884 Fix/login redirect

- package-lock.json
- package.json
- src/DataDictionary/DataDictionary.css
- src/DataDictionary/DataDictionary.jsx
- src/DataDictionary/graph/Canvas/Canvas.css
- src/DataDictionary/graph/Canvas/Canvas.jsx
- src/DataDictionary/graph/Legend/Legend.css
- src/DataDictionary/graph/Legend/Legend.jsx
- src/DataDictionary/graph/NodePopup/NodePopup.css
- src/DataDictionary/graph/NodePopup/NodePopup.jsx
- src/DataDictionary/graph/OverlayPropertyTable/OverlayPropertyTable.css
- src/DataDictionary/graph/OverlayPropertyTable/OverlayPropertyTable.jsx
- src/DataDictionary/reducers.js
- src/DataDictionary/search/DictionarySearchHistory/DictionarySearchHistory.css
- src/DataDictionary/search/DictionarySearcher/DictionarySearcher.css
- src/DataDictionary/table/DataDictionaryNode/DataDictionaryNode.css
- src/DataDictionary/table/DataDictionaryNode/index.jsx
Jira link: https://ctds-planx.atlassian.net/browse/PXP-5834
Several changes increasing accessibility of Data Dictionary:
- Table view is now the default (this is a requirement from the NIH testing team)
- Ensure that elements have focus outlines
- Ensure that clickable elements can be activated using the keyboard
Related accessibility PRs in gen3-ui-component: 
- https://github.com/uc-cdis/gen3-ui-component/pull/68
- https://github.com/uc-cdis/gen3-ui-component/pull/69
- Make Data Dictionary view 508 compliant
- Pin portal's version of gen3-ui-component to 0.5.1, which includes accessibility improvements
> (PXP-5834): Make Data Dictionary 508 compliant

- src/Indexing/Indexing.jsx
- src/actions.js
- Fixes an issue in the indexing GUI where the spinner spins forever if the presigned URL has an incorrect request signature
> fix: invalid presigned URL issue

- src/Indexing/Indexing.jsx
- src/components/Popup.jsx
Deployed in https://zakir.planx-pla.net/indexing
- Added value attributes to the download buttons in the indexing GUI that contain links to the target files
> Add value attribute to indexing GUI buttons

- src/Covid19Dashboard/IllinoisMapChart/index.jsx
- src/Covid19Dashboard/WorldMapChart/index.jsx
- src/Covid19Dashboard/index.jsx
Deployed in https://qa-covid19.planx-pla.net for testing
- Use only `open-JHU` data to calculate `selectedDate`
- Pass filtered data to child map components in props
> fix: use only filtered data for maps

- src/Indexing/Indexing.jsx
- Increase Indexing GUI s3 upload timeout.
> fix: indexing gui timeout

- package-lock.json
- package.json
- src/Login/Login.jsx
- src/Login/ReduxLogin.js
- src/index.jsx
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-5062 (https://occ-data.atlassian.net/browse/COV-16) 
The login button now will be disabled and display a spinner as well as an exploantory tooltip while waiting for fetching login options from fence or in case some error happened during the fetching
Deployed in https://mingfei.planx-pla.net/login
- Login button will be disabled and display a spinner as well as an exploantory tooltip while loading login options
> PXP-5062 COV-16 Feat/spinner login

- src/Login/Login.jsx
fix console error: "Failed prop type: The prop `label` is marked as required in `Button`, but its value is `undefined`."
> Fix console error

- src/components/IndexButtonBar.css
- Allow index buttons with long content to flex vertically to fit.
> flex text content of index button

- src/Indexing/Indexing.jsx
Deployed in https://zakir.planx-pla.net/indexing
- Now handling an error case in the Indexing GUI where the Fence /data/upload endpoint returns 500.
> feat: catching new error case in indexing GUI

- src/DataDictionary/table/DataDictionaryTable/DataDictionaryTable.jsx
- src/DataDictionary/table/DataDictionaryTable/DataDictionaryTable.test.jsx
Addresses https://ctds-planx.atlassian.net/browse/PXP-6370
- removes Internal from dictionary table
> filter internal category nodes from dictionary table

- src/workspaceIndex.jsx
[PXP-6684](https://ctds-planx.atlassian.net/browse/PXP-6684)
* fix missing routes in `workspaceIndex.jsx`
* fix missing routes in `workspaceIndex.jsx`
> fix(workspaceIndex): missing no-access routes

- docs/study_viewer.md
- src/StudyViewer/SingleStudyViewer.jsx
- src/StudyViewer/StudyCard.jsx
- src/StudyViewer/StudyDetails.jsx
- src/StudyViewer/StudyViewer.css
Jira Ticket: [PXP-6920](https://ctds-planx.atlassian.net/browse/PXP-6920)
- Study viewer improvements: configurable buttons in study viewer configuration; buttons can be hidden on the list view or on the single item view; request access redirection modal improvements
> PXP-6920 Study viewer improvements

- docs/study_viewer.md
- package-lock.json
- package.json
- src/StudyViewer/StudyDetails.jsx
Jira Ticket: [PXP-6946](https://ctds-planx.atlassian.net/browse/PXP-6946)
Add optional `accessRequestedText` and `accessRequestedTooltipText` fields for `request_access` button in study viewer to optionally override the default text and optionally add a tooltip for that button
The fix of the alignement is in https://github.com/uc-cdis/gen3-ui-component/pull/81
- Add optional `accessRequestedText` and `accessRequestedTooltipText` fields for `request_access` button in study viewer
> add accessRequestedText and accessRequestedTooltipText

- docs/limited_flie_pfb_export.md
- Update to correct service versions
> Update docs for limited file pfb export

- src/StudyViewer/StudyDetails.jsx
Jira Ticket: [PXP-6974](https://ctds-planx.atlassian.net/browse/PXP-6974)
- Study viewer: improve the handling of 409 errors from Requestor
> PXP-6974 Requestor 409 better handling

- docs/study_viewer.md
- src/Covid19Dashboard/PlotChart/index.jsx
- src/StudyViewer/StudyDetails.jsx
- src/StudyViewer/reduxer.js
Jira Ticket: [PXP-7037](https://ctds-planx.atlassian.net/browse/PXP-7037)
- Study viewer: add configuration to disable buttons for an item
- Fix COVID charts bug when Guppy returns 401
> PXP-7037 Feat/display button field

- docs/study_viewer.md
- src/StudyViewer/StudyViewer.jsx
- src/nctIndex.css
Jira Ticket: [PXP-7063](https://ctds-planx.atlassian.net/browse/PXP-7063)
- Configurable study viewer items order
> PXP-7063 Configurable study viewer items order

- docs/portal_config.md
- src/ResourceBrowser/ResourceBrowser.css
- src/ResourceBrowser/index.jsx
- src/Workspace/Workspace.less
- src/Workspace/index.jsx
- src/localconf.js
Jira Ticket: COV-146
- Update workspace text from "Launching workspace..." to "Launching Workspace, this process may take several minutes"
- Add optional "workspacePageDescription" configuration
> Configurable workspace description

- src/index.ejs
- webpack.config.js
one more place with hard coded DAP url
> fix hardcoded dap url

- src/Analysis/AnalysisApp.css
- src/Analysis/AnalysisApp.jsx
Jira Ticket: [PXP-7236](https://ctds-planx.atlassian.net/browse/PXP-7236)
- Added fullscreen button for iframe apps
> PXP-7236 Feature/fullscreen button analysis app

- src/StudyViewer/StudyDetails.jsx
- Fix a bug causing the study viewer page to crash if no request access button configured
> fix: sv not crash if no req access button

- src/Covid19Dashboard/IllinoisMapChart/index.jsx
- src/Covid19Dashboard/WorldMapChart/index.jsx
- src/Covid19Dashboard/index.jsx
Jira Ticket: COV-464
- PRC dashboard: Display simulation plots for all US counties
> PRC: Display simulation plots for all US counties

- src/GuppyDataExplorer/ExplorerTable/index.jsx
- src/GuppyDataExplorer/ExplorerVisualization/index.jsx
- src/GuppyDataExplorer/configTypeDef.js
Jira Ticket: [PXP-6032](https://ctds-planx.atlassian.net/browse/PXP-6032)
keep track if sorting is done using the field attribute and sort after field mapping if it has not already been done
> (PXP-6032):fix/table-column-sorting: keep track if sorting is done and sort after field mapping if it has not already been done

- src/Covid19Dashboard/IllinoisMapChart/index.jsx
- src/Covid19Dashboard/WorldMapChart/index.jsx
Jira Ticket: COV-595
bug introduced in https://github.com/uc-cdis/data-portal/pull/773
- Covid-19 dashboard: fix US charts not loading because of an undefined variable
> Fix PRC charts displaying undefined

- docs/portal_config.md
- package-lock.json
- package.json
- src/GuppyDataExplorer/ExplorerVisualization/index.jsx
This PR fulfills: https://ctds-planx.atlassian.net/browse/PXP-7378
Add new chart type support `fullPie`, which will be rendered as a full pie chart
Related PR: https://github.com/uc-cdis/gen3-ui-component/pull/87
Example config:
> "ethnicity": {
>      "chartType": "fullPie"
>      "title": "Ethnicity"
> }
Deployed to: https://qa-midrc.planx-pla.net/explorer (under the `Subjects` tab)
- Add new chart type support `fullPie`, which will be rendered as a full pie chart
- Gen3-ui-component: up to 0.6.4
> PXP-7378 Feat/full pie

- src/Covid19Dashboard/IllinoisMapChart/index.jsx
- src/Covid19Dashboard/WorldMapChart/index.jsx
Jira Ticket: [COV-643](https://ctds-planx.atlassian.net/browse/COV-643)
don't do `Number("<5").toLocaleString()`
fix PRC maps showing NaN when data is not a number
> (COV-643):bug/mapsNaNbug: fix maps showing NaN when data is not a number

- dev.html
- src/index.ejs
Deployed in https://mingfei.planx-pla.net/
- Import bold font for Roboto and Martel explicitly
> fix bold font

- src/Covid19Dashboard/index.jsx
- src/localconf.js
Jira Ticket: [COV-574](https://occ-data.atlassian.net/browse/COV-574)
Add auspice tab for Illinois
> feat(il): add il tab

- package-lock.json
- src/GuppyDataExplorer/ExplorerVisualization/ExplorerVisualization.css
Jira Ticket: [PXP-7435](https://ctds-planx.atlassian.net/browse/PXP-7435)
remove word-break css should not be needed
> (PXP-7435): fix/dataExplorerWordWrap: remove word-break css

- src/Covid19Dashboard/PlotChart/index.jsx
- src/Covid19Dashboard/index.jsx
Jira Ticket: [COV-644](https://occ-data.atlassian.net/browse/COV-644)
space x axis dynamically based on how many items are in the data set
> (COV-644):feat/xAxisLabelSpacing: space x axis dynamically

- src/Workspace/index.jsx
Jira Ticket: [PXP-7560]https://ctds-planx.atlassian.net/browse/PXP-7560
- Add pop confirm to "Terminate Workspace" button
[PXP-7560]: https://ctds-planx.atlassian.net/browse/PXP-7560
> PXP-7560: Add popconfirm to "terminate workspace" button

- src/Workspace/index.jsx
Jira Ticket: [PXP-7220](https://ctds-planx.atlassian.net/browse/PXP-7220)
Fix for issue 2 in above ticket
- Make workspace iframe acquire focus on ready to prevent keyboard issue
> PXP-7220 fix: acquire foucs for ws iframe when ready

- package-lock.json
- src/Analysis/GWASApp.jsx
- src/Analysis/ReduxGWASApp.js
- src/authMappingUtils.js
Jira Ticket: [PXP-7561](https://ctds-planx.atlassian.net/browse/PXP-7561)
Display warning banner to user and disable job submission button if the user don't have mariner access permission
Mariner access policy is checked by resource `/mariner`, service `mariner`, method `access`
Sample screenshot
Deployed in: https://qa-mickey.planx-pla.net/
Login with your personal gmail if you want to see this
- Display warning banner to user and disable job submission button if the user don't have mariner access permission
> PXP-7561 feat: alert user if lack of mariner permission

- src/Covid19Dashboard/IllinoisMapChart/index.jsx
- src/Covid19Dashboard/WorldMapChart/index.jsx
Jira Ticket: [COV-553](https://occ-data.atlassian.net/browse/COV-553)
- update map ranges
- change component logic so it does not run unnecessarily
> (COV-553): feat/updateMapRanges: update map ranges

- docs/portal_config.md
- src/Workspace/index.jsx
- src/localconf.js
Jira Ticket: [COV-671](https://occ-data.atlassian.net/browse/COV-671)
- Add Workspace Page Title property to display a title on Workspace Page
- Convert workspace Description to have a div holder so more html can be used in description
> (COV-671): feat/PRCWorkspaceUI: add Workspace Page Title property

- src/Covid19Dashboard/IllinoisMapChart/index.jsx
- src/Covid19Dashboard/WorldMapChart/index.jsx
Jira Ticket: [COV-806](https://occ-data.atlassian.net/browse/COV-806)
- fix Homepage maps sometimes showing no data/ gray
> (COV-806): fix/homepageMapError: check for data before using

- src/Layout/reducers.js
- src/Layout/reduxer.js
- src/components/layout/NavBar.jsx
- src/components/layout/NavButton.jsx
Jira Ticket: [PXP-7399](https://ctds-planx.atlassian.net/browse/PXP-7399)
change the way activeTab is set so that it always highlights which page the user is on
> (PXP-7399): fix/highlightActiveNavItem: change the way activeTab is set

- src/Covid19Dashboard/ControlPanel/ControlPanel.less
Jira Ticket: [COV-829](https://occ-data.atlassian.net/browse/COV-829)
- make map legend slightly transparent
> (COV-829): style/mapLegend: make map legend slightly transparent

- docs/portal_config.md
- package-lock.json
- src/authMappingUtils.js
- src/components/Introduction.jsx
- src/components/layout/TopBar.jsx
- src/components/tables/TransactionLogTable.jsx
- src/localconf.js
Jira Ticket: [PXP-7888](https://ctds-planx.atlassian.net/browse/PXP-7888)
Make Arobrist UI be able to hide link/button to `/submission` for users who don't have permission to submit data.
Added new optional config `hideSubmissionIfIneligible` to control this feature, must be used together with `useArboristUI`
This is part of the requirement in [PXP-7888](https://ctds-planx.atlassian.net/browse/PXP-7888), note the "restrict access" feature is not included in this PR.
This PR would fulfill the urgent need from MIDRC for now, but for the long run we should plan an improvement to the existing Arborist UI feature as a core product feature. Here is the JIRA ticket https://ctds-planx.atlassian.net/browse/PXP-7946 (there is a design doc in that ticket)
Deploy and tested in: …
> PXP-7888 Feat/arborist UI topbar

- src/Covid19Dashboard/index.jsx
see https://github.com/uc-cdis/covid19-tools/commit/27a7ebabb713bd314a3580cba477badf4e74283f#diff-a94d81f93df7fd3e60737f3921b6053bc3d392d3dbd5b6ec58babdae48e0fb6cR23
- Update the path to the PRC top10 chart data
> Update the path to the PRC top10 chart data

- docs/portal_config.md
- package-lock.json
- package.json
- src/GuppyDataExplorer/ExplorerFilter/index.jsx
- src/localconf.js
Jira Ticket: [COV-816](https://occ-data.atlassian.net/browse/COV-816)
- add explorerHideDataFilter and pass it through to guppy
Update @gen3/guppy dependency to version 0.13.0
> (COV-816): feat/explorerHideDataFilter: pass filter flag through to guppy

- docs/portal_config.md
> chore: update doc

- .travis.yml
- Dockerfile
- package-lock.json
- package.json
Clear npm cache arbitraryly at the end of docker image building process, try to mitigate portal stuck at start up issues
> fix: clear npm cache

- src/Covid19Dashboard/Covid19Dashboard.less
- src/Covid19Dashboard/IllinoisMapChart/index.jsx
Jira Ticket: [COV-766](https://occ-data.atlassian.net/browse/COV-766)
- make PRC main map respond better to larger and smaller browser widths
> (COV-766): style/prcResponsive: make map respond better to larger and smaller browser widths

- src/Covid19Dashboard/ChartCarousel/index.jsx
- src/Covid19Dashboard/Covid19Dashboard.less
- src/Covid19Dashboard/index.jsx
Jira Ticket: [COV-843](https://occ-data.atlassian.net/browse/COV-843)
- add popup to charts on PRC homepage
> (COV-843): feat/chartPopup: add popup to charts

- src/Discovery/aggMDSUtils.jsx
* Remove field <-> column mappings and API calls in favor of the API handling mappings https://github.com/uc-cdis/metadata-service/pull/25
> feat(api-updates): update UI for API changes

- src/components/Popup.jsx
- fixed a bug causing popup mask to disappear for user logout popups
> fix: popup mask

- src/Workspace/index.jsx
- fixed a bug causing the workspace fullscreen button to malfunction
> fix: ws fullscreen btn

- src/actions.js
Jira Ticket: [PXP-8396](https://ctds-planx.atlassian.net/browse/PXP-8396)
- Fixed a bug causing graphql query to malfunction on query page
> PXP-8396 fix: graph query fetcher

- src/Discovery/Discovery.css
- src/Discovery/Discovery.tsx
- src/Discovery/DiscoveryListView.tsx
[HP-312](https://ctds-planx.atlassian.net/browse/HP-312)
Make the height of adv search filters updated better according to the table's height
- Discovery: fix a bug causing adv filter panel to cutoff
> HP-312 Fix/adv filter height

- src/Covid19Dashboard/ChartCarousel/ChartCarousel.less
- src/Index/page.less
Jira Ticket: [COV-966](https://occ-data.atlassian.net/browse/COV-966)
Fix broken carousel styling introduced in release 3.0.0
> (COV-966): fix/GraphCarouselNavigation: fix carousel styling

- src/Covid19Dashboard/ReduxCovid19Dashboard.js
- src/Covid19Dashboard/index.jsx
Jira Ticket: [COV-931](https://occ-data.atlassian.net/browse/COV-931)
add vaccine total to IL page
> (COV-931): feat/totalVaccinated: add vaccine total to il page

- src/Discovery/Discovery.tsx
Jira Ticket: [HP-352](https://ctds-planx.atlassian.net/browse/HP-352)
- Discovery page: Links in table and study pages now open in new tab instead of navigating away from Discovery page.
> (HP-352) Open contentType: link in new tab

- .travis.yml
test disable npm cache in Travis
> fix: disable travis npm cache

- src/Discovery/Discovery.tsx
- src/Discovery/DiscoveryActionBar.tsx
- src/Discovery/DiscoveryConfig.d.ts
Jira Ticket: https://ctds-planx.atlassian.net/browse/HP-522
- If configured, check that all external OIDCs in WTS are signed in before export to WS, direct download
- To enable this check, set `features.exportToWorkspace.verifyExternalLogins` flag to true in gitops
> Check all WTS OIDCs are signed in before download/export to WS

- src/CoreMetadata/CoreMetadataHeader.jsx
Jira Ticket: [PXP-7952](https://ctds-planx.atlassian.net/browse/PXP-7952)
- have file download button call indexd to check if user can download file
> (PXP-7952): feat/downloadCallIndexd: have File download button call indexd

- docs/portal_config.md
- src/Discovery/Discovery.tsx
- src/Discovery/DiscoveryConfig.d.ts
Jira Ticket: https://ctds-planx.atlassian.net/browse/HP-580
- Add config for setting name of tags column on discovery page
> Add tag column name configuration option

- docs/study_viewer.md
- src/StudyViewer/reduxer.js
Jira Ticket: [PXP-9116](https://ctds-planx.atlassian.net/browse/PXP-9116)
- hide empty fields with new flag
> (PXP-9116): feat/studyViewerHideEmpty: hide empty fields with new flag

- docs/portal_config.md
- docs/study_viewer.md
- src/StudyViewer/ExportToWorkspace.jsx
- src/StudyViewer/SingleStudyViewer.jsx
- src/StudyViewer/StudyCard.jsx
- src/StudyViewer/StudyDetails.jsx
- src/StudyViewer/StudyViewer.jsx
- src/StudyViewer/reduxer.js
Jira Ticket: [PXP-8880](https://ctds-planx.atlassian.net/browse/PXP-8880)
- Add button to export study to workspace 
- Add documentation for new button
- Add messaging for when export is in progress
> (PXP-8880): Feat/study viewer export to workspace

- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Jira Ticket: [PXP-8735](https://ctds-planx.atlassian.net/browse/PXP-8735)
- Do not display the "Export PFB to workspace" button to users without workspace access
> PXP-8735 No 'export pfb to workspace' w/o access to workspace

- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Jira Ticket: PXP-9189
Updated data-portal dropdown menu title when loginForDownload flag is enabled.
> updated dropdown button title in midrc

- src/components/layout/FooterNIAID.jsx
Jira Ticket: [PXP-9248](https://ctds-planx.atlassian.net/browse/PXP-9248)
* Update NIAID Clinical Trials Footer with `HHS responsible disclosure link`
> (PXP-9248): Add HHS responsible disclosure link to NIAID Clinical Trials

- docs/portal_config.md
Add 'footer.links' to portal config documentation
> Add 'footer.links' to portal config documentation

- src/components/layout/FooterNIAID.jsx
Jira Ticket: [PXP-9378](https://ctds-planx.atlassian.net/browse/PXP-9378)
* Update the HHS Footer link in NIAID Commons
> (PXP-9378): NCT: Update the HHS link

- src/Discovery/Discovery.tsx
Jira Ticket: [PXP-9847](https://ctds-planx.atlassian.net/browse/PXP-9847)
- Discovery: fixed a bug so now array content will show up in discovery table with proper concatenation
> PXP-9847 fix: array display

- docs/portal_config.md
> Fix `detailView` docs

- docs/study_viewer.md
- src/StudyViewer/StudyDetails.jsx
- src/StudyViewer/reduxer.js
Jira Ticket: [PXP-9835](https://ctds-planx.atlassian.net/browse/PXP-9835)
- Study viewer: add flag to check for idp login type before allowing user to request access
> (PXP-9835): feat/studyViewerIdpFlag: add flag to check for idp login type before allowing user to request access

- docs/study_viewer.md
- src/StudyViewer/StudyDetails.jsx
- src/StudyViewer/reduxer.js
Jira Ticket: [PXP-9838](https://ctds-planx.atlassian.net/browse/PXP-9838)
- add flag to specify field for external file download
> (PXP-9838): feat/studyViewerExternalDownload: add flag to specify field for external file download

- src/Analysis/GWASUIApp/CaseControlGWAS.jsx
Jira Ticket: [PXP-9987](https://ctds-planx.atlassian.net/browse/PXP-9987)
- New step in Case-Control wizard that allows the user to review the covariates selection, displaying some statistics regarding the number of missing samles.
> Add review covariates step

- src/Analysis/GWASUIApp/QuantitativeGWAS.jsx
Jira Ticket: [PXP-9955](https://ctds-planx.atlassian.net/browse/PXP-9955)
- New filter logic to allow only the selection of variables of the type "continuous"
> filtering concepts to allow only continuous ones to be selected

- src/Analysis/GWASUIApp/QuantitativeGWAS.jsx
Jira Ticket: [PXP-10037](https://ctds-planx.atlassian.net/browse/PXP-10037)
- using new concept id for HARE
> adjust HARE concept id

- src/Analysis/GWASUIApp/GWASJob.jsx
Jira Ticket: [PXP-10027](https://ctds-planx.atlassian.net/browse/PXP-10027)
- update workflow description with workflow name
- manual
> feat add workflow name

- src/Analysis/GWASUIApp/CaseControlGWAS.jsx
Jira Ticket: [PXP-10030](https://ctds-planx.atlassian.net/browse/PXP-10030)
- new QC check that gives an error if case and control cohorts have overlapping populations
- improved covariates display in the review submission step
> Add overlap check

- src/Analysis/GWASUIApp/CaseControlGWAS.jsx
- src/Analysis/GWASUIApp/QuantitativeGWAS.jsx
Jira Ticket: [PXP-10057](https://ctds-planx.atlassian.net/browse/PXP-10057)
- retrieve covariates by concept type
- more consistent naming between quantitative and case-control gwas modules
> using new cohort-middleware endpoint for fetching covariates by concept type

- src/Discovery/DiscoveryActionBar.tsx
Jira Ticket: [HP-791](https://ctds-planx.atlassian.net/browse/HP-791)
- Add `repositoryName` to DD RUM actions for `manifestDownload`, `datasetDownload` and `exportToWorkspace`
> HP-791 add repo name to rum actions

- src/Covid19Dashboard/ControlPanel/index.jsx
- src/Covid19Dashboard/IllinoisMapChart/index.jsx
Jira Ticket: [COV-1156](https://occ-data.atlassian.net/browse/COV-1156)
* Updated Citations for google mobility data
> Added Citations for Google Mobility Data

- src/Analysis/GWASUIApp/CaseControlGWAS.jsx
- src/Analysis/GWASUIApp/QuantitativeGWAS.jsx
Jira Tickets: 
[PXP-10020](https://ctds-planx.atlassian.net/browse/PXP-10020)
[PXP-10028](https://ctds-planx.atlassian.net/browse/PXP-10028)
- the HARE concept_id is now passed on to the argo-wrapper so that the workflow can use it in its requests to cohort-middleware (e.g. the CSV data request)
- HARE selection is now mandatory and validated as such
> Add HARE concept id in submit & make HARE selection mandatory

- src/Analysis/GWASUIApp/QuantitativeGWAS.jsx
Jira Ticket: NA / bug
- fixes bug in submit request of Quantitative wizard
- remove dead code
> Fix quantitative outcome and covariates submit

- src/Analysis/GWASUIApp/GWASJob.jsx
Jira Ticket: [PXP-10096](https://ctds-planx.atlassian.net/browse/PXP-10096)
- option to view logs for failed jobs
> View logs for failed jobs

- src/Discovery/DiscoveryDetails.tsx
Jira Ticket: [BMH-161](https://ctds-planx.atlassian.net/browse/BMH-161)
- Discovery: fixed a bug causing extra `/` presents in the generated permalink
> BMH-161 fix: permalink

- docs/portal_config.md
- src/index.ejs
- webpack.config.js
Jira Ticket: [HP-822](https://ctds-planx.atlassian.net/browse/HP-822)
add meta description to site header as an optional config field
> (HP-822): feat/metaDescription: add meta description to site header as an optional config field

- src/Workspace/index.jsx
- Workspace: fixed a bug causing workspace page to crash if no pay model is set
> fix: don't crash

- src/StudyRegistration/StudyRegistrationRequestForm.tsx
- src/Workspace/ErrorWorkspacePlaceholder.jsx
Jira Ticket: [HP-832](https://ctds-planx.atlassian.net/browse/HP-832)
* Update text in Registration Access request confirmation page.
> (HP-832): update text in Registration Access request confirmation page

- src/Discovery/DiscoveryDetails.tsx
- webpack.config.js
Jira Ticket: [HP-831](https://ctds-planx.atlassian.net/browse/HP-831)
- Discovery: fixed a bug causing active tab status didn't get reset after closing the details view
- Misc: fixed a bug causing webpack devserver websocket connection get rejected by host/origin issue
> HP-831 Fix active tab

- src/Discovery/Discovery.tsx
- src/Discovery/DiscoveryListView.tsx
Jira Ticket: [HP-820](https://ctds-planx.atlassian.net/browse/HP-820)
Add explaination tooltips to table rows and checkboxes
Screenshots:
- Discovery: add explaination tooltips to table rows and checkboxes
> HP-820 add tooltip to columns

- src/Analysis/GWASWizard/GWASCaseControl.jsx
Small changes to test in steps 1/2/3 in case-control flow to make more clear.
> feat(text): slight changes to user facing text in case-control

- src/Analysis/GWASWizard/GWASQuantitative.jsx
- src/Analysis/GWASWizard/shared/WorkflowParameters.jsx
1. add missing tour button to quant workflow set parameter
2. add space between set parameter name and input box
> fix add space for parameter name and input, add missing tour button

- docs/portal_config.md
- src/StudyRegistration/StudyRegistration.css
- src/StudyRegistration/StudyRegistrationRequestForm.tsx
- src/localconf.js
Jira Ticket: [HP-828](https://ctds-planx.atlassian.net/browse/HP-828)
* Add disclaimer text to Study Registration form.
> (HP-828) chore: add disclaimer to registration

- src/StudyViewer/StudyDetails.jsx
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> Study viewer fix typo

- src/StudyRegistration/StudyRegistration.tsx
Jira Ticket: [HP-833](https://ctds-planx.atlassian.net/browse/HP-833)
Clearing state variable on button press for registering another study
> [HP-833] resetting study id on return to study registration page

- src/Analysis/GWASWizard/shared/CustomDichotomousSelect.jsx
Jira Ticket: [VADC-96](https://ctds-planx.atlassian.net/browse/VADC-96)
- add header for dichotomous variable step
> feat add diachotomous headers

- src/StudyViewer/StudyDetails.jsx
Jira Ticket: [PXP-10206](https://ctds-planx.atlassian.net/browse/PXP-10206)
- show info message when user is not logged in with correct credentials
> (PXP-10206): feat/studyViewerInfo: show info message when user is not logged in with correct credentials

- src/Analysis/GWASWizard/GWASCaseControl.jsx
Jira Ticket: [VADC-92](https://ctds-planx.atlassian.net/browse/VADC-92)
case control gwas submission without mandatory covariate selection
> feat(VADC-92): allow gwas submit w/o covs cc

- src/Analysis/GWASWizard/shared/GWASJob.jsx
Jira Ticket: [VADC-141](https://ctds-planx.atlassian.net/browse/VADC-141)
download inputs button was missing for submitted jobs that completed
> fix(VADC-141): succeed typo

- src/Analysis/GWASWizard/shared/GWASFormSubmit.jsx
Jira Ticket: [VADC-7](https://ctds-planx.atlassian.net/browse/VADC-7)
- reveal submission error
> feat reveal submission error

- src/Analysis/GWASWizard/shared/CustomDichotomousSelect.jsx
Jira Ticket: [VADC-117](https://ctds-planx.atlassian.net/browse/VADC-117)
remove displayed cohort ids for custom dichotomous pairs
> fix(VADC-117): remove cd pair description

- src/Analysis/AnalysisApp.jsx
Jira Ticket: [VADC-135](https://ctds-planx.atlassian.net/browse/VADC-135)
- disable interaction with page when reactour is present
> fix disable interaction when in reactour

- src/Analysis/GWASWizard/CovariateStatsByHareCC.jsx
- src/Analysis/GWASWizard/shared/WorkflowParameters.stories.jsx
- src/Analysis/GWASWizard/shared/useDebounce.js
Jira Ticket: [VADC-13](https://ctds-planx.atlassian.net/browse/VADC-13)
- debounce expensive endpoint call that updates the HARE dropdown
> debounce expensive endpoint call

- src/Analysis/GWASWizard/GWASCaseControl.jsx
- src/Analysis/GWASWizard/shared/GWASFormSubmit.jsx
- src/Analysis/GWASWizard/shared/WorkflowParameters.jsx
Jira Ticket: [VADC-179](https://ctds-planx.atlassian.net/browse/VADC-179)
- covariates in step 5 does not disable if there's only 1 covariate left
- outcome covariate shown in outcome section of final step
- outcome covariate not shown in covariate section of final step
- hide reactour in step 4 of case control when covariate table is empty
https://user-images.githubusercontent.com/86243966/190019777-58aa70f4-78eb-4747-b667-27a6a46b3b4f.mov
> fix missing outcome name and outcome in covariates

- src/Analysis/GWASWizard/CohortOverlap.jsx
- src/Analysis/GWASWizard/CovariateStatsByHareCC.jsx
- src/Analysis/GWASWizard/shared/WorkflowParameters.stories.jsx
- src/Analysis/GWASWizard/wizardEndpoints/cohortMiddlewareApi.js
Jira Ticket: [VADC-173](https://ctds-planx.atlassian.net/browse/VADC-173)
- HARE dropdown now automatically removes overlap between case/cohort and reports only the non-overlapping populations sizes.
> Remove overlap case control

- src/Analysis/GWASWizard/GWASCaseControl.jsx
- src/Analysis/GWASWizard/shared/GWASFormSubmit.jsx
- spacing issue in case control step 2
- final step null variable error
> fix null outcome concept_id in case control

- src/Analysis/GWASWizard/GWASCaseControl.jsx
- src/Analysis/GWASWizard/GWASQuantitative.jsx
- src/Analysis/GWASWizard/shared/GWASFormSubmit.jsx
- src/Analysis/GWASWizard/shared/gwasSteps.js
Jira Ticket: [VADC-139](https://ctds-planx.atlassian.net/browse/VADC-139)
- reactour wording
> fix reactour changes

- src/Analysis/GWASWizard/CohortOverlap.jsx
- make cohort overlap message more apparent
> fix cohort overlap warning

- src/Analysis/GWASWizard/shared/AttritionTable.jsx
- src/Analysis/GWASWizard/shared/AttritionTable.stories.jsx
- src/Analysis/GWASWizard/shared/AttritionTableRow.jsx
- src/Analysis/GWASWizard/wizardEndpoints/cohortMiddlewareApi.js
small fixes to ongoing Attrition table branch
> Prs to attrition table

- docs/portal_config.md
* Add `clinicalTrialFields` in `studyRegistrationConfig` that was accidentally deleted in `portal_confg.md`.
> Update portal_config.md with `clinicalTrialFields`

- src/Analysis/GWASWizard/GWASCaseControl.jsx
- src/Analysis/GWASWizard/GWASQuantitative.jsx
- src/Analysis/GWASWizard/shared/gwasSteps.js
- reactour for next in quant
- reactour for attrition table
> fix quant next step bug, attirition table reactour

- src/Analysis/GWASWizard/shared/AttritionTable.jsx
- src/Analysis/GWASWizard/shared/AttritionTable.stories.jsx
Jira Ticket: [VADC-203](https://ctds-planx.atlassian.net/browse/VADC-203)
- fix the column type for dichotomous covariate
- update corresponding storybook test
> fix attrition table type column

- package-lock.json
- package.json
Jira Ticket: [MIDRC-58](https://ctds-planx.atlassian.net/browse/MIDRC-58)
* updating Guppy to version 0.15.2 to fix bug with download TSV/CSV formats button in Explorer
> dep: update Guppy to 0.15.2, needs to fix button to download TSV/CSV formats

- src/actions.js
Jira Ticket:
https://ctds-planx.atlassian.net/browse/BRH-259
If no externally connected commons, return results from local arborist in portal
Make sure to follow the DEV guidelines (https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Describe what this pull request does.
- Add short descriptive bullet points for each section if relevant. Keep in mind that they will be parsed automatically to generate official release notes.
- Test manually.
- Maintain or increase the test coverage (if relevant).
- Update the documentation, or justify if not needed.
-->
- return local arborist if no externally connected commons
> return local arborist if no externally connected commons

- src/Analysis/GWASUIApp/GWASUIApp.css
> fix attrition table style

- docs/portal_config.md
- src/Discovery/Discovery.tsx
- src/Discovery/index.tsx
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- Fix discovery page errors when `features.authorization` is enabled but `features.authorization.supportedValues` is not configured
> Fix discovery page 'supportedValues' failures

- src/Analysis/AnalysisApp.jsx
- src/Analysis/GWASV2/GWASContainer.jsx
- src/Analysis/GWASWizard/shared/constants.js
- src/localconf.js
beginning steps template combined gwas
> feat(VADC-261): add combined gwas steps template

- src/Analysis/AnalysisApp.jsx
- src/Analysis/GWASUIApp/GWASUIApp.jsx
- src/Analysis/GWASUIApp/GWASWorkflowList.jsx
- src/Analysis/GWASUIApp/GWASWorkflowList.stories.jsx
- src/Analysis/GWASWizard/GWASCaseControl.jsx
- src/Analysis/GWASWizard/GWASQuantitative.jsx
- src/Analysis/GWASWizard/shared/GWASJob.jsx
Jira Ticket: [VADC-134](https://ctds-planx.atlassian.net/browse/VADC-134)
- workflow list now will refresh every 5s
- workflow details are fetched once at 1st render and again only fetched again if the status of the workflow changes
- depends on the changes made in https://github.com/uc-cdis/argo-wrapper/pull/67
> Improve workflow list refresh

- src/Discovery/DiscoveryDetails.tsx
* Apply the discovery detail active-tab fix to the back button.
> fix: apply the discovery detail active-tab fix to back button

- src/Discovery/DiscoveryDetails.tsx
- src/Discovery/aggMDSUtils.jsx
* Fix discovery page errors when tags are empty
> fix: skip empty tags in discovery page

- package-lock.json
- package.json
- src/Analysis/GWASV2/Shared/CohortsOverlapDiagram/CohortsOverlapDiagram.jsx
- src/Analysis/GWASV2/Shared/CohortsOverlapDiagram/CohortsOverlapDiagram.stories.jsx
- src/Analysis/GWASV2/Shared/CohortsOverlapDiagram/Simple3SetsEulerDiagram.jsx
- src/Analysis/GWASV2/Shared/CohortsOverlapDiagram/Simple3SetsEulerDiagram.stories.jsx
- src/Analysis/GWASV2/Shared/wizardEndpoints/cohortMiddlewareApi.js
Jira Ticket: [VADC-83](https://ctds-planx.atlassian.net/browse/VADC-83)
- New Euler diagram visualization component that retrieves data from cohort-middleware "check-overlap" endpoint
- Added "@upsetjs/venn.js": "^1.4.2"
> Feat/vadc Euler diagram

- src/Login/ProtectedContent.jsx
try to fix state update logic error
> fix state update

- src/Discovery/Discovery.tsx
Jira Ticket: [HP-900](https://ctds-planx.atlassian.net/browse/HP-900)
* Handle null values in discovery page
> (HP-900): handle null value

- src/Analysis/GWASV2/Components/AttritionTableWrapper/AttritionTableWrapper.stories.jsx
- fix: added SourceContext to fix storybook
> fix: add SourceContext to fix storybook

- README.md
- docs/guide_running_portal_locally.md
- src/Covid19Dashboard/standalone/README.md
- Update the guide to run data-portal locally
> Update guide to run portal locally

- .eslintrc.js
- .github/workflows/ci.yaml
- .gitignore
- src/Discovery/DiscoveryActionBar.tsx
- src/StudyRegistration/StudyRegistrationRequestForm.tsx
Jira Ticket: [PPS-149](https://ctds-planx.atlassian.net/browse/PPS-149)
Fix for XSS
SSRFs are false positives
- Misc: security updates
> PPS-149 Fix/pps149

- src/Analysis/GWASV2/GWASContainer.jsx
Jira Ticket: [[VADC-377](https://ctds-planx.atlassian.net/browse/VADC-377)](https://ctds-planx.atlassian.net/browse/[VADC-377](https://ctds-planx.atlassian.net/browse/VADC-377))
- disable next button when no HARE has been selected yet
> Fix/disable next when no HARE selected

- .eslintrc.js
- .gitignore
- .stylelintrc.js
- package.json
- src/GuppyDataExplorer/ExplorerTable/index.jsx
- src/GuppyDataExplorer/ExplorerVisualization/index.jsx
- src/Workspace/WorkspaceRefreshToken.js
- Workspace: do callback within debounce time
> fix: callback within debounce

- src/StudyRegistration/StudyRegistrationRequestForm.tsx
- src/StudyRegistration/utils.tsx
- src/WorkspaceRegistration/WorkspaceRegistration.tsx
Jira Ticket: [HP-1011](https://ctds-planx.atlassian.net/browse/HP-1011)
- Access Request (Study/Workspace): now can prevent user from creating extra tickets if they already have a same request pending
- Access Request (Study/Workspace): Improved message display
> HP-1011 Fix reg req access

- nginx.conf
Jira Ticket: [PPS-143](https://ctds-planx.atlassian.net/browse/PPS-143)
- block access to some files
[PPS-143]: https://ctds-planx.atlassian.net/browse/PPS-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update nginx conf

- src/Discovery/index.tsx
- Hook was calling multiple times for every checkbox click
> fix react hook on discovery page

- src/components/Popup.jsx
- src/components/Popup.less
Jira Ticket: N/A
* disable scrolling for background for DUA
* improving DUA positioning and showing "Accept" button only after scroll
> fix: dua position and scrolling

- src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Jira Ticket: N/A
* fix for spinner for manifest button not showing until the count
> fix: proper spinner for manifest count

- src/Analysis/AnalysisApp.jsx
- src/localconf.js
Jira Ticket: [VADC-456](https://ctds-planx.atlassian.net/browse/VADC-456)
- Add new temporary entry to VA QA, for testing the new GWAS Results Viewer App features
[VADC-456]: https://ctds-planx.atlassian.net/browse/VADC-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat: add GWASResultsV2 app

- src/Covid19Dashboard/index.jsx
Moved COVID-19 Community Analysis Tab to the first position as requested by Bob
> moved COVID-19 Community Analysis Tab to first

- src/Workspace/index.jsx
- src/WorkspaceRegistration/WorkspaceRegistration.tsx
- src/ecosystemIndex.jsx
- src/index.jsx
Jira Ticket: [[HP-1066](https://ctds-planx.atlassian.net/browse/HP-1066)]
Change workspace registration title and url location
[HP-1066]: https://ctds-planx.atlassian.net/browse/HP-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> portal update for workspace registration

- src/CoreMetadata/reduxer.js
- src/Covid19Dashboard/Covid19Dashboard.less
- src/Covid19Dashboard/index.jsx
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> Fix PRC homepage class name

- .github/labeler.yml
- .github/workflows/labeler.yml
> Label PRs to run only relevant tests

- nginx.conf
Jira Ticket: [PPS-212](https://ctds-planx.atlassian.net/browse/PPS-212)
Reverts uc-cdis/data-portal#1286
code has been moved to cloud-automation
[PPS-212]: https://ctds-planx.atlassian.net/browse/PPS-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert "(PPS-212):add header to prevent clickjacking"

- src/Analysis/GWASResultsV2/Views/Home/Home.jsx
- src/Analysis/GWASResultsV2/Views/Home/Home.stories.jsx
Jira Ticket: [VADC-552](https://ctds-planx.atlassian.net/browse/VADC-552)
- Add message to spinner while loading the main table in Results app
[VADC-552]: https://ctds-planx.atlassian.net/browse/VADC-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat: add message to spinner while loading the main table in Results app

- src/CoreMetadata/CoreMetadataHeader.jsx
Jira Ticket: [PXP-10908](https://ctds-planx.atlassian.net/browse/PXP-10908)
Add no access description for File page
[PXP-10908]: https://ctds-planx.atlassian.net/browse/PXP-10908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(no-access): add no access message

- src/CoreMetadata/CoreMetadataHeader.jsx
Jira Ticket: [PXP-10908](https://ctds-planx.atlassian.net/browse/PXP-10908)
[PXP-10908]: https://ctds-planx.atlassian.net/browse/PXP-10908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-10908 Update file download page message

- package-lock.json
- package.json
- updating guppy to 0.16.0
- will require server to also be using guppy ^0.16.0 on backend
> chore/updateGuppy: updating guppy to 0.16.0

- src/components/Popup.less
Jira Ticket: N/A
* `fixed` position should fix the bug where popup appear in the hidden (scrolled past) area
> fix: use fixed position for popup

- src/Analysis/GWASResults/Utils/gwasWorkflowApi.js
- src/Analysis/GWASResults/Views/Home/Home.stories.jsx
- src/Analysis/GWASResults/Views/Home/HomeTable/ActionsDropdown/ActionsDropdown.jsx
- src/Analysis/GWASResults/Views/Home/HomeTable/ActionsDropdown/ActionsDropdown.test.jsx
Jira Ticket: [VADC-498](https://ctds-planx.atlassian.net/browse/VADC-498)
- Integrate argo-wrapper call to retry failed workflows
[VADC-498]: https://ctds-planx.atlassian.net/browse/VADC-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat/retry GWAS workflow

- src/Discovery/Discovery.tsx
- src/Discovery/index.tsx
- src/Discovery/reducers.js
Jira Ticket: [HP-1157](https://ctds-planx.atlassian.net/browse/HP-1157)
- fix bug where filters dont reset table to page one
[HP-1157]: https://ctds-planx.atlassian.net/browse/HP-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (HP-1157): fix bug where filters dont reset table to page one

- docs/study_viewer.md
- add to requiredIdpField docs to better explain what is going on
> add to requiredIdpField docs to better explain what is going on

- src/Analysis/GWASResults/Views/Input/AttritionTable/AttrtitionTableWrapper.jsx
- src/Analysis/GWASResults/Views/Input/JobDetails/JobDetails.jsx
Jira Ticket: [VADC-644](https://ctds-planx.atlassian.net/browse/VADC-644)
- adjust labels shown in GWAS Results Input view to make sure they are the same as the ones shown in GWAS App
[VADC-644]: https://ctds-planx.atlassian.net/browse/VADC-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: adjust labels shown in GWAS Results Input view

- src/Discovery/Discovery.tsx
- src/Discovery/DiscoveryDetails.tsx
Jira Ticket: [PXP-11042](https://ctds-planx.atlassian.net/browse/PXP-11042)
- Discovery page update tooltip text
[PXP-11042]: https://ctds-planx.atlassian.net/browse/PXP-11042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PXP-11042): Discovery page update tooltip text

- src/Discovery/index.tsx
Jira Ticket: [PXP-11040](https://ctds-planx.atlassian.net/browse/PXP-11040)
- add more options to Discovery page isAuthorized check 
[PXP-11040]: https://ctds-planx.atlassian.net/browse/PXP-11040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-11040: add more options to Discovery page isAuthorized check

- src/Analysis/GWASApp/GWASContainer.jsx
- src/Analysis/GWASApp/Steps/ConfigureGWAS/ConfigureGWAS.jsx
- src/Analysis/GWASApp/Utils/constants.js
Jira Ticket: [VADC-672](https://ctds-planx.atlassian.net/browse/VADC-672)
Updates GWAS App so when user has a finalPopulationSize containing an object with a size value of zero, it renders a warning message and prevents the user from advancing to the next step (viewing the modal). 
Note that the finalPopulationSize array contains objects for one or more of the following: case, control and the total based on the selected HARE Ancestry. 
[VADC-672]: https://ctds-planx.atlassian.net/browse/VADC-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(blockSubmissionGroupSizeZero): initial commit

- docs/portal_config.md
- src/Layout/reducers.js
- src/Layout/reduxer.js
- src/components/Banner.jsx
- src/components/layout/TopBar.jsx
- src/reducers.js
- src/reduxStore.js
Jira Ticket: [PXP-7377](https://ctds-planx.atlassian.net/browse/PXP-7377)
- add banner to portal
[PXP-7377]: https://ctds-planx.atlassian.net/browse/PXP-7377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PXP-7377): add banner to portal

- src/Discovery/DiscoveryActionBar.tsx
- src/localconf.js
- webpack.config.js
Jira Ticket: [HP-1194](https://ctds-planx.atlassian.net/browse/HP-1194)
- only allow certain data on HEAL to be available for download with InCommon IdP login
[HP-1194]: https://ctds-planx.atlassian.net/browse/HP-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (HP-1194): Allow access to specific open data based on IdP

- src/StudyViewer/StudyViewer.jsx
- fix study viewer alphabetical ordering
> (PXP-11062): fix study viewer alphabetical ordering

- docs/portal_config.md
- src/covid19Index.jsx
- src/ecosystemIndex.jsx
- src/index.jsx
- src/localconf.js
- src/nctIndex.jsx
- src/workspaceIndex.jsx
- webpack.config.js
- Move ddUrl for RUM to configuration, instead of hardcoding - This is necessary for the move to datadog govcloud.
> move ddUrl to portal config

- src/Discovery/DiscoveryDetails.tsx
- Discovery: fixed a bug causing the details page to crash when encountering null values
> fix value is null

- docs/portal_config.md
- src/GuppyDataExplorer/ExplorerTable/index.jsx
- src/GuppyDataExplorer/ExplorerVisualization/index.jsx
Jira Ticket: N/A
* new configuration variable for DICOM Viewer URL, similar to `dicomViewerId`; have default value to support old deployments
* new configuration variable for DICOM Server URL, similar to `dicomViewerId`; have default value to support old deployments
> extra configuration for DICOM Viewer

- src/GuppyDataExplorer/ExplorerTable/index.jsx
Fix #1432 `dicomViewerUrl is not defined` and `dicomServerURL is not defined` errors in explorer page
> Fix dicom viewer/server url logic

- webpack.config.js
Jira Ticket: [PXP-11139](https://ctds-planx.atlassian.net/browse/PXP-11139)
- Misc: update CSP to unblock GA actions
[PXP-11139]: https://ctds-planx.atlassian.net/browse/PXP-11139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-11139 Fix/ga csp

- src/Discovery/DiscoveryActionBar.tsx
Jira Ticket: [HP-1233](https://ctds-planx.atlassian.net/browse/HP-1233)
- Generalize IdP-based access control
[HP-1233]: https://ctds-planx.atlassian.net/browse/HP-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (HP-1233): Generalize IdP-based access control

- src/Analysis/AnalysisApp.jsx
- src/Analysis/SharedUtils/TeamProject/Utils/CheckForTeamProjectApplication.js
- src/Analysis/SharedUtils/TeamProject/Utils/CheckForTeamProjectApplication.test.js
- src/localconf.js
Jira Ticket: [VADC-781](https://ctds-planx.atlassian.net/browse/VADC-781)
- allow teamProject to be configured in `gitops.json` instead of hard-coding in frontend code
- configuration now needs to be added to `gitops.json` 
[VADC-781]: https://ctds-planx.atlassian.net/browse/VADC-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat: allow teamProject to be configured in gitops.json instead of hard-coding in frontend code

- src/Index/nctPage.jsx
- remove webform from NCT homepage
> remove webform from NCT homepage

- src/Analysis/GWASApp/Components/Covariates/CustomDichotomousCovariates.jsx
- src/Analysis/GWASApp/Components/Covariates/CustomDichotomousCovariates.stories.jsx
- src/Analysis/GWASApp/Components/SelectCohort/SelectCohort.jsx
- src/Analysis/GWASApp/Components/SelectCohort/SelectCohort.stories.jsx
- src/Analysis/GWASApp/Components/SelectCohort/SelectCohortDropDown.jsx
- src/Analysis/GWASApp/Components/SelectCohort/SelectCohortDropDown.stories.jsx
- src/Analysis/GWASApp/Components/SelectCohort/Utils/CohortDefinitions.jsx
- src/Analysis/GWASApp/GWASContainer.jsx
- src/Analysis/GWASApp/Steps/SelectCovariates/SelectCovariates.jsx
- src/Analysis/GWASApp/Steps/SelectOutcome/SelectOutcome.jsx
- src/Analysis/GWASApp/Steps/SelectStudyPopulation/SelectStudyPopulation.jsx
- src/Analysis/GWASApp/Utils/cohortMiddlewareApi.js
Jira Ticket: [VADC-799](https://ctds-planx.atlassian.net/browse/VADC-799)
* Updates Cohort Middleware API endpoints to use team project, updates storybooks associated with Cohort Middleware API calls with team project
* Shows error message now for error status from Cohort Definitions endpoint request
[VADC-799]: https://ctds-planx.atlassian.net/browse/VADC-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(cohortMiddleWareEndpointUpdate): Initial commit

- src/GuppyDataExplorer/ExplorerTable/index.jsx
- src/Workspace/index.jsx
Jira Ticket: [MIDRC-550](https://ctds-planx.atlassian.net/browse/MIDRC-550)
Before:
After:
- Replace nested empty values with 'null' in explorer display
[MIDRC-550]: https://ctds-planx.atlassian.net/browse/MIDRC-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MIDRC-550 Replace nested empty values with 'null' in explorer display

- src/Index/nctPage.jsx
per doc: https://docs.google.com/document/d/1jKlJHzjHmHL_8tlwmdLoRhpeHile5ZmBa7bqYynmzI0/edit
Request 3.
> Change mailto link to explicit email address

- docs/study_viewer.md
- src/StudyViewer/reduxer.js
- Study viewer: always query the configured "defaultOrderBy" field
> Query the study viewer 'order by' field

- src/Analysis/AnalysisApp.jsx
- src/Analysis/AtlasDataDictionary/AtlasDataDictionaryButton/AtlasDataDictionaryButton.test.jsx
Jira Ticket: [VADC-937](https://ctds-planx.atlassian.net/browse/VADC-937)
- Fix card title to start with MVP
[VADC-937]: https://ctds-planx.atlassian.net/browse/VADC-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update card title to MVP instead of Atlas

- src/Analysis/GWASApp/Utils/cohortMiddlewareApi.js
Jira Ticket: [VADC-926](https://ctds-planx.atlassian.net/browse/VADC-926)
* Ensures data source used by CohortMiddlewareApi getSources function is delivered in expected format or throws error. 
[VADC-926]: https://ctds-planx.atlassian.net/browse/VADC-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(addTypeCheckToDataSource): ran linter

- src/Discovery/DiscoveryDetails/DiscoveryDetails.tsx
Jira Ticket: [HP-1402](https://ctds-planx.atlassian.net/browse/HP-1402)
- Discovery: fixed an issue that array values are incorrectly flattened for list components
[HP-1402]: https://ctds-planx.atlassian.net/browse/HP-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HP-1402 fix incorrectly flattening array

- src/StudyRegistration/StudyRegistration.tsx
Link to JIRA ticket if there is one: [HP-1426](https://ctds-planx.atlassian.net/browse/HP-1426)
- Add openICPSR as an option for repo selection 
[HP-1426]: https://ctds-planx.atlassian.net/browse/HP-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add openICPSR to repo selection list

- src/StudyRegistration/StudyRegistration.tsx
Link to JIRA ticket if there is one:
Update help language per [HP-1491](https://ctds-planx.atlassian.net/browse/HP-1491) for clarity. 
Removes 'Dataverse' per [HP-1500](https://ctds-planx.atlassian.net/browse/HP-1500) as it has been updated to 'Harvard Dataverse' 
[HP-1491]: https://ctds-planx.atlassian.net/browse/HP-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HP-1500]: https://ctds-planx.atlassian.net/browse/HP-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update repo selection help StudyRegistration.tsx

- nginx.conf
Closes #1537
- Remove the nginx routing regex pattern specific to file extensions, so it won't match for project IDs that contain a "."
> Remove the nginx routing regex pattern specific to file extensions

- src/Discovery/DiscoveryDropdownTagViewer.tsx
- src/Discovery/DiscoveryTagViewer.tsx
- src/Discovery/Utils/Search/filterByTags.ts
- Discovery: fixed a bug causing the page to crash due to inappropriately handling optional tags field
> fix: better handling optional tags field in metadata

- src/GuppyDataExplorer/ExplorerTable/index.jsx
Link to JIRA ticket if there is one: [MIDRC-153](https://ctds-planx.atlassian.net/browse/MIDRC-153)
- Fix explorer table header sorting issue
[MIDRC-153]: https://ctds-planx.atlassian.net/browse/MIDRC-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (MIDRC-153): Fix explorer table header sorting issue

- src/Analysis/SharedUtils/TeamProject/TeamProjectModal/TeamProjectModal.jsx
- src/Analysis/SharedUtils/TeamProject/TeamProjectModal/TeamProjectModal.stories.jsx
Link to JIRA ticket if there is one: [VADC-1158](https://ctds-planx.atlassian.net/browse/VADC-1158)
- Update Team Projects Modal for use case where user does not have teams available
- Add storybook page for new Modal
[VADC-1158]: https://ctds-planx.atlassian.net/browse/VADC-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (VADC-1158): Update Team Projects Modal for use case where user does not have teams available

- src/StudyRegistration/utils.tsx
Link to JIRA ticket if there is one:  https://ctds-planx.atlassian.net/browse/HP-1565
- Study reg: fixed a bug causing pre-defined data repository metadata got overwritten by user
> HP-1565 fix repo info overwrite

- src/Analysis/AnalysisApp.jsx
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1221
- use openid URL for Atlas to get automatic login behavior in Atlas UI
Depends on https://github.com/uc-cdis/gitops-qa/pull/2919
> Fix: better atlas url

- src/StudyViewer/StudyDetails.jsx
https://ctds-planx.atlassian.net/browse/NIAID-14
Add support for hyperlinks in the study viewer detailed description.
> -Add support for hyperlink tags in study viewer detailed description

- src/authMappingUtils.js
Link to JIRA ticket if there is one: [MIDRC-565](https://ctds-planx.atlassian.net/browse/MIDRC-565)
* Consider `*` as one of the included values when checking for `create` and `update` permissions
[MIDRC-565]: https://ctds-planx.atlassian.net/browse/MIDRC-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Consider '*' as a wildcard

- src/Workspace/WorkspaceRefreshToken.js
- src/actions.js
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/PXP-11357
Improve the way portal handle the response from WTS to not redirect back to WTS login page if it fails
Improve the way portal handle the response from WTS to not redirect back to WTS login page if it fails
> fix to properly handle the response from wts

- src/Analysis/GWASApp/Components/JobInputModal/JobInputModal.jsx
- src/Analysis/GWASApp/Components/JobInputModal/JobInputModal.stories.jsx
- src/Analysis/GWASApp/Components/JobInputModal/JobInputModal.test.jsx
- src/Analysis/GWASApp/Components/JobInputModal/WorkflowLimitsModalErrorMessage/WorkflowLimitsModalErrorMessage.css
- src/Analysis/GWASApp/Components/JobInputModal/WorkflowLimitsModalErrorMessage/WorkflowLimitsModalErrorMessage.jsx
- src/Analysis/GWASApp/Components/JobInputModal/WorkflowLimitsModalErrorMessage/WorkflowLimitsModalErrorMessage.test.jsx
https://ctds-planx.atlassian.net/browse/VADC-1268
**Design:**
**Implementation:** 
Note that submit button is disabled and shows loading spinner until service for checking their workflow limit is done loading.
No server response
Invalid server response data (i.e. malformed data)
Successful response and over workflow limit
Successful response and under workflow limit
Adds error messages and prevents submission to GEN3 GWAS App job input modal when user has exceeded their allotted workflow limit, or if the service for checking their workflow limit doesn't respond or provides malformed data.
> Feat/gwas app workflow limit error UI

- docs/portal_config.md
- src/Analysis/AnalysisApp.jsx
- src/Login/ProtectedContent.jsx
- src/components/AccessDenied.jsx
- src/covid19Index.jsx
- src/ecosystemIndex.jsx
- src/index.jsx
- src/localconf.js
- src/nctIndex.jsx
Link to JIRA ticket if there is one:  
https://ctds-planx.atlassian.net/browse/VADC-1286, 
https://ctds-planx.atlassian.net/browse/VADC-1228,  
https://ctds-planx.atlassian.net/browse/VADC-1221
- add access-denied page and flag to enable when user does not have access to any site resources
- fix: use openid URL for Atlas to get automatic login behavior
> Feat: login features

- data/config/acct.json
- data/config/anvil.json
- data/config/bpa.json
- data/config/canine.json
- data/config/dcf.json
- data/config/default.json
- data/config/gtex.json
- data/config/ibdgc.json
- data/config/ncrdc-demo.json
- data/config/ndh.json
- data/config/va.json
- docs/portal_config.md
- src/Analysis/GWASApp/Components/JobInputModal/WorkflowLimitsModalErrorMessage/WorkflowLimitsModalErrorMessage.jsx
- src/Analysis/GWASApp/Components/JobInputModal/WorkflowLimitsModalErrorMessage/WorkflowLimitsModalErrorMessage.test.jsx
- src/Analysis/GWASResults/Views/Home/HomeTable/ActionsDropdown/ActionsDropdown.jsx
- src/Analysis/SharedUtils/WorkflowLimitsDashboard/WorkflowLimitsDashboard.jsx
- src/Analysis/SharedUtils/WorkflowLimitsDashboard/WorkflowLimitsDashboard.test.jsx
- src/GenericAccessRequestForm/Constants/FormSpecificConstants.tsx
- src/Workspace/ErrorWorkspacePlaceholder.jsx
- src/Workspace/index.jsx
- src/components/ErrorPage403.jsx
update all support emails from <whatever-support>@datacommons.io to <whatever-support>@gen3.org
do not merge until gen3.org emails are active.
> Update support emails from @datacommons.io to @gen3.org

- src/Discovery/Discovery.css
- src/Discovery/Discovery.tsx
- src/Discovery/DiscoveryAccessibilityLinks.tsx
- testSchema.sh
- Discovery: the location and padding for accessiblity links are no longer hard coded
> fix: don't hard code discovery accessbility link location

- src/GenericAccessRequestForm/Constants/FormSpecificConstants.tsx
Fix mixed usage of plain strings and fucntions
- Fixed a bug causing access request form to crash when displaying result
> fix change access form text type

- src/Analysis/SharedUtils/AccessibilityUtils/Accessibility.css
- src/Analysis/SharedUtils/TeamProject/TeamProjectModal/TeamProjectModal.jsx
Link to JIRA ticket if there is one:  [VADC-1420](https://ctds-planx.atlassian.net/browse/VADC-1420)
**Before**
**After**
* Fixed modal button color to #215C9E to ensure accessibility
[VADC-1420]: https://ctds-planx.atlassian.net/browse/VADC-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VADC-1420: Fixed modal button color to ensure accessibility

- src/Analysis/SharedUtils/TeamProject/Utils/teamProjectApi.js
- src/Analysis/SharedUtils/TeamProject/Utils/teamProjectApi.test.js
- src/Discovery/index.tsx
https://ctds-planx.atlassian.net/browse/VADC-1541
Make front end team project role function look for specific read permission
QA user without team project permission without fix
qa user without team project permission with fix
> Update team project filter

- src/Popup/ReduxAuthTimeoutPopup.jsx
- src/SessionMonitor/index.js
Link to JIRA ticket if there is one: [VADC-1448](https://ctds-planx.atlassian.net/browse/VADC-1448)
- add logout warning to session manager 
[VADC-1448]: https://ctds-planx.atlassian.net/browse/VADC-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (VADC-1448): add logout warning

- .github/workflows/integration_tests.yaml
- src/UserProfile/UserProfile.jsx
- src/components/layout/Footer.jsx
- src/components/layout/NavBar.jsx
- src/components/layout/TopBar.jsx
- src/covid19Index.jsx
- src/ecosystemIndex.jsx
- src/index.jsx
- src/nctIndex.jsx
- src/workspaceIndex.jsx
Link to JIRA ticket if there is one: [VADC-1455](https://ctds-planx.atlassian.net/browse/VADC-1455) [VADC-1454](https://ctds-planx.atlassian.net/browse/VADC-1454) [VADC-1424](https://ctds-planx.atlassian.net/browse/VADC-1424)
- fix misplaced html ul element
- refactor header and nav elements
- add aria labels to nav elements 
[VADC-1455]: https://ctds-planx.atlassian.net/browse/VADC-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VADC-1454]: https://ctds-planx.atlassian.net/browse/VADC-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VADC-1424]: https://ctds-planx.atlassian.net/browse/VADC-1424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (VADC-1455, VADC-1454, VADC-1424): mis 508 fixes

- docs/portal_config.md
- src/Analysis/SharedUtils/TeamProject/TeamProjectModal/TeamProjectModal.css
- src/Analysis/SharedUtils/TeamProject/Utils/teamProjectApi.js
- src/Analysis/SharedUtils/TeamProject/Utils/teamProjectApi.test.js
- src/Discovery/DiscoveryActionBar/DiscoveryActionBar.tsx
- src/Discovery/DiscoveryActionBar/components/OpenFillRequestFormButton.tsx
- src/Discovery/DiscoveryConfig.d.ts
- src/Discovery/DiscoveryListView.tsx
- src/Discovery/index.tsx
- src/Login/Login.jsx
- src/Popup/ReduxAuthTimeoutPopup.jsx
- src/SessionMonitor/index.js
- src/UserProfile/UserProfile.jsx
- src/components/AccessDenied.jsx
- src/components/AccessDenied.less
- src/components/layout/Footer.jsx
- src/components/layout/NavBar.jsx
- src/components/layout/TopBar.jsx
- src/covid19Index.jsx
- src/ecosystemIndex.jsx
- src/index.jsx
- src/nctIndex.jsx
- src/workspaceIndex.jsx
Merge master into release branch 22
> Merge master into release branch 22 

- .secrets.baseline
- docs/portal_config.md
- src/Analysis/Analysis.jsx
- src/Analysis/AnalysisApp.jsx
- src/Login/Login.jsx
- src/ResourceBrowser/index.jsx
- src/UserProfile/UserProfile.jsx
- src/Workspace/index.jsx
- src/localconf.js
Link to JIRA ticket if there is one: [VADC-1415](https://ctds-planx.atlassian.net/browse/VADC-1415) [VADC-1412](https://ctds-planx.atlassian.net/browse/VADC-1412) [VADC-1413](https://ctds-planx.atlassian.net/browse/VADC-1413) [VADC-1456](https://ctds-planx.atlassian.net/browse/VADC-1456)
- add configurable title to Profile page
- update h2s to h1s for main page headings to conform with ADA standards 
- Login page
- Apps page
- Individual Apps
- Workspace page
- Profile page
- Resource browser
[VADC-1415]: https://ctds-planx.atlassian.net/browse/VADC-1415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VADC-1412]: https://ctds-planx.atlassian.net/browse/VADC-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> (VADC-1415 VADC-1412 VADC-1413 VADC-1456): Refactor level one headings

- src/Login/Login.jsx
Link to JIRA ticket if there is one: [VADC-1559](https://ctds-planx.atlassian.net/browse/VADC-1559)
* change "blow" typo to "below"
[VADC-1559]: https://ctds-planx.atlassian.net/browse/VADC-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: typo "blow" to "below"

- Dockerfile
- package-lock.json
- package.json
- src/Analysis/GWASApp/Components/JobInputModal/JobInputModal.test.jsx
https://ctds-planx.atlassian.net/browse/PPS-1678
- update jest
- update cross-spawn
> PPS-1678 update jest and cross-spawn

- package-lock.json
- package.json
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/PPS-1728
- update guppy to 0.20.1
> PPS-1728 update guppy

- data/config/default.json
- data/getTexts.js
- src/localconf.js
- update expolrer config example in default config file
> update default config

- src/Analysis/GWASApp/Utils/gwasWorkflowApi.js
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1587
- improve job submission message by adding concept_id of the selected HARE population
> Feat: add hare_population_concept_id to job submission JSON

- data/dictionary.json
- src/Discovery/DiscoveryActionBar/DiscoveryDataLibrary.tsx
- Create list from Discovery dropdown.
> Create list from dropdown

- src/StudyRegistration/StudyRegistration.tsx
add Gene Expression Omnibus (GEO) as a new repo option in the HEAL Study Registration repo drop-down
> Update StudyRegistration.tsx - add GEO

- .github/workflows/ci.yaml
Link to JIRA ticket if there is one:
> Native arm builds

- src/Analysis/SharedUtils/TeamProject/TeamProjectModal/TeamProjectModal.jsx
https://ctds-planx.atlassian.net/browse/VADC-1685
all email references that currently are vadc@lists.uchicago.edu → change to vadc-support@gen3.org
For Feb 17 release
> Update TeamProjectModal.jsx - update VADC email

- src/components/layout/ExternalFooter.tsx
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/HP-1959
- use fractional height value for external footer
> fix use fractional height value

- src/components/Icon.jsx
- src/img/icons/blank.svg
- src/img/icons/index.jsx
- Misc: Add an default blank icon for nav bar buttons to prevent it from crashing
> add a default blank icon for nav bar

- .storybook/main.js
- .storybook/webpack.config.js
- package-lock.json
- package.json
- src/PrivacyPolicy/PrivacyPolicy.stories.jsx
- src/PrivacyPolicy/ReduxPrivacyPolicy.js
- webpack.config.js
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/PPS-1786
- replace `showdown` with `marked`
> PPS-1786 Fix/replace showdown

- src/Login/Login.jsx
https://ctds-planx.atlassian.net/browse/DCF-2048
- Adding specifc classname to each login option to allow application of special styling if needed.
https://github.com/uc-cdis/cdis-manifest/pull/8592
> Add specific class to each login button

- package-lock.json
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/PPS-1984
- update `@babel/runtime-corejs3` to 7.27.1
> PPS-1984 update @babel/runtime-corejs3

- src/index.jsx
- fixed a bug cause access request form unable to submit in Gen3 bundle
> use the correct access request form in gen3 bundle
