src/Explorer/ExplorerTable.jsx
=> fix(align): fix align right file size

package-lock.json, package.json
eliminates dependency on marked which github was
flagging due to a known vulnerability (that didn't affect us,
but update anyway)
=> fix(dependency): update graphiql version

data/getSchema.js, src/actions.js, src/index.ejs, src/localconf.js
=> fix(shib): add shibbleth configuration

src/DataModelGraph/ReduxDataModelGraph.js, src/Login/ProtectedContent.jsx, src/Submission/ProjectSubmission.jsx, src/actions.js
Data-portal freaks out when new commons comes up with no projects.
Also fixes to avoid gdcapi oauth dance (now deprecated with jwt) for non-403 peregrine responses.
=> fix(login): better handle new empty commons

src/CoreMetadata/CoreMetadataHeader.jsx, src/CoreMetadata/CoreMetadataTable.jsx, src/CoreMetadata/reduxer.js, src/components/FileTypePicture.jsx
Instead of a broken link, display an error on the landing page if there's no metadata
=> PXD-1430 fix(core-metadata)

data/parameters.js, src/components/layout/NavButton.less
The "Exploration" button will go to the new data explorer when in the default/Generic Data Commons app. Also fixed a quick bug I noticed with outlines in the nav bar.
@thanh-nguyen-dang just wanted to make sure that only we use the default/Generic Data Commons config in parameters.js right? This won't be used by anyone external?
=> PXD-1491 Link to new Explorer page in dev

src/DataModelGraph/utils.js, src/DataModelGraph/utils.test.js
A node can be visited more than once, as we want it to go to its lowest possible level in the tree, but we still want to detect cycles that could cause infinite loops. By mapping out the descendants of each node beforehand, we can avoid reprocessing nodes that are further up the tree than a given node and avoid cycles. This adds O(n) time up front.
=> PXD-1262 Fix dictionary graph crashing

src/DataExplorer/DataExplorerVisualizations.jsx, src/components/charts/helper.js, src/components/charts/helper.test.js
Current counts and charts in visualizations only shows bucket numbers in the filters, but we want the visualization result shows actual number of selected items in the filters. To solve this, we use `sqon` to calculate the correct numbers.
=> PXD-1514 fix(explorer): use sqon to calculate actual number of selected items

src/components/tables/DataExplorerTable/DataExplorerTable.less
Hid it in the CSS because I didn't see an "enabled prop" in Arranger for the search bar ¯\_(ツ)_/¯
=> PXD-1944 Hide table search bar

src/Arranger/ArrangerWrapper.jsx, src/DataExplorer/index.jsx
`qa-mickey` was loading very slowly because `ArrangerWrapper` was querying all fields (~800) in order to render the charts, when it only needed 3 fields. This fixes that.
I think that the Arranger code needs to be refactored overall, so this is just a fix for before I leave for vacation. I've created a ticket (PXD-2172) to refactor the code to be more intuitive (and faster!) for when I get back.
=> Only query fields for charts

src/components/charts/SummaryHorizontalBarChart/SummaryHorizontalBarChart.less, src/components/charts/SummaryPieChart/SummaryPieChart.less
Add `display: hidden` style for rechart's measurement span element to hide it.
- Hide the measurement div from recharts
=> fix(recharts): recharts measurement span is supposed to be hidden

src/DataDictionary/DataModelStructure/DataModelStructure.jsx
Fix spelling on a button in the dictionary viewer.
Spelling fix.
=> fix(spelling): button in dictionary viewer

nginx.conf
pidgin has paths like `/file/bla.foo/id` - so the nginx rule that treats any path with `.` as a file and 404 if it doesn't exist needs update
=> fix(nginx.conf): ignore . in folder names

src/components/FileTypePicture.jsx
Display the right file type image in the core metadata landing page
The default image was displayed all the time
=> fix(file-img): display the right file type image

package-lock.json, package.json, src/index.jsx
Using older versions of react you can start the webpack with no problem but with newer versions there is no support for the onTap listener
=> removing tap event that was removed in newer versions of react

src/CoreMetadata/CoreMetadataHeader.jsx
If we use `expires_in=10`, we get the following error:
Fail to reach AWS: Parameter validation failed: Invalid range for parameter DurationSeconds, value: 10, valid range: 900-inf
- set `expires_in` to 900 when requesting a presigned URL for file download
=> fix(download)

src/DataDictionary/graph/GraphCalculator/graphStructureHelper.js
Fix bug: When there's a loop in dictionary, routing finding will cause `Maximum call stack exceeded` error
=> fix(loop): avoid loop in route finding

data/config/acct.json, data/config/anvil.json, data/config/bhc.json, data/config/bpa.json, data/config/dcf.json, data/config/default.json, data/config/edc.json, data/config/gtex.json, data/config/ibdgc.json, data/config/kf.json, data/config/kfDcfInterop.json, data/config/ncrdc-demo.json, data/config/ndh.json, data/dictionary.json, src/DataExplorer/DataExplorerVisualizations.jsx
The ETL has gotten rid of `node_id` in the newest version - to accommodate this change and each commons being on a different version of the ETL we need to add a new config field. 
Also added a new title for the login page while I was here.
- Changes title on the login page
- Adds a config field for getting the number of cases/subjects/etc.
=> Fix Explorer configuration

Dockerfile, package-lock.json, package.json
There's warning message from docker image build, and ui-component is using npm prepared compiled files under `dist`. This PR solves the warning and add a flag to `npm ci` to allow docker generate prepared files. 
- Fix warning from fsevents packages during docker image building
- Add flag to `npm ci` in dockerfile to support npm prepared files from `ui-component` library
=> fix(docker): add flag to npm ci and remove unused package to avoid warning

data/config/default.json, src/Index/utils.js
Portal config has some merge process that will take default.json's `homepageChartNodes`, this will cause bugs for commons not using gitops.json. This PR remove the `homepageChartNodes` config block from default config to avoid that. 
- remove `homepageChartNodes` block from default config
=> fix(config): remove default config for tiered access

src/DataDictionary/graph/NodePopup/NodePopup.css, src/DataDictionary/table/DataDictionaryNode/DataDictionaryNode.css
There're some style bugs for buttons in the dd graph viewer's node popup and in graph table. This PR changes some CSS to fix them. 
- Fix some dd graph button off style bugs
=> fix(dd-button-bug): tiny css changes to fix dd graph button off style

src/QueryNode/QueryNode.jsx, src/QueryNode/ReduxQueryNode.js
The page that displays the records for a project can take a long time to load since it is querying all the submissions - this changes that to only query the first 20 (sorted by date) so a user can validate that their submission succeeded. Added text to clarify this is no longer the full list, but only the most recent 20.
- Changing query from 10,000 to 20
- Page won't time out
=> Change query to only pull first 20 records

src/Workspace/Workspace.less
fix(Workspace): remove web-kit-fill-available, prevents jupyter notebook from expanding beyond size of screen, so there is no scrolling issue
Page no longer jumps, as the iframe no longer expands enough to scroll.
=> Workspace Scroll Bugfix

src/DataExplorer/DataExplorerVisualizations.jsx, src/DataExplorer/arrangerQueryHelper.js
If case number greater than 10k, arranger query returns error. This PR add limitation to only get first 10k, to avoid UI break. 
- add arranger query limit to first 10000 to avoid err response
=> fix(limit): add arranger query limit to first 10000

data/config/ncrdc-demo.json, data/config/ndh.json, data/config/va.json, src/DataExplorer/actionHelper.js
Not sure why we did that and it's too slow for mickey with that call
just send case_id to file index to get object_id is sufficient
- improve export to workspace performance
=> fix(export): skip one unnecessary call

data/config/va.json
Changes Mickey to display number of Patients instead of Clinical Supplements on homepage
- More relevant number on homepage for mickey
=> Change to Patients in Mickey

runWebpack.sh, src/Login/ProtectedContent.jsx, src/SessionMonitor/SessionMonitor.test.js, src/SessionMonitor/index.js, src/actions.js, src/index.jsx, src/localconf.js, webpack.config.js
This PR focuses on the user session lifecycle. Deployed at https://zakir.planx-pla.net/
-> The query page now calls updateSession() before executing a query. This fixes the bug where query results come back empty with a 200 response in the case where the user's session has expired. 
-> The refreshSession function now hits /user/user instead of just /user, so that we can notify the user with the ReduxAuthTimeoutPopup if their session is over (/user is public, /user/user is not). 
-> The SessionMonitor no longer logs out users. If a user has been inactive and the config has logoutInactiveUsers == true, we just decline to refresh their session and allow Fence to log them out. At this point, we start using Sheepdog to check their auth status instead of Fence, so that we can check their auth …
=> Fix login logout issues - PXP-3000

src/SessionMonitor/SessionMonitor.test.js, src/SessionMonitor/index.js
Qingya found a small bug in the function isUserOnPage in the SessionMonitor -- the updateSession function logs out an inactive user in the workspace if the URL ends with a slash. This PR fixes that issue.
=> fix: account for trailing slashes in URLs

.travis.yml, package.json
It's quite annoying/useless to do a relay after npm install (and sometimes it cause error because local config) so I will just remove it. 
- remove useless post-install just to speed up local developing
=> fix(post): move usedless post-install, to speedup local dev

src/Index/relayer.js, src/components/charts/IndexBarChart/index.jsx
It happens in IBDGC portal: For index chart config block inside portal config, when only 2 or less nodes are provided, the chart component will crash. This PR add more out-of-index check and refine the initialization logic. 
- fix  index chart crash bug when less than 3 nodes
=> fix(chart): fix index chart crash when less than 3 nodes provided

src/CoreMetadata/CoreMetadataHeader.jsx, src/index.ejs, src/localconf.js, webpack.config.js
In Unity Portal deployment, sub-portals should have `"fence_hostname": "https://master.domain.com/"` in `manifest.json`. Mind the trailing slash!
- Add support for external Fence
=> feat(unity): support Unity Portal

src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- Guppy export to workspace flow was using incorrect manifest format and was including entries with undefined object_ids, resulting in a 400 response from the manifest service
=> fix: guppy explorer getManifest function returned incorrect format

data/config/gtex.json, src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
- Download manifest and export to workspace capability from file explorer
- updated locally stored config to be in sync with gitops
- require `fileExplorerConfig` block with `buttons`
=> Add download/export buttons for file explorer

src/Index/reduxer.jsx, src/components/IndexButtonBar.jsx
Builds on this PR https://github.com/uc-cdis/data-portal/pull/565 
Disables index button bars (card thingies?) based on Arborist access.
So if for example you have the following `componentToResourceMapping` block in gitops.json: 
```
"componentToResourceMapping": {
"Analyze Data" : {
"resource": "/workspace",
"method": "access",
"service": "jupyterhub"
}
}
```
then only users with `/workspace` will see the Analyze Data card on the home page. 
- Disable index button bars based on Arborist access
=> feat(idx-button-auth): hide idx button if no auth

src/Workspace/Workspace.less, src/Workspace/index.jsx
(PXP-4217) https://ctds-planx.atlassian.net/browse/PXP-4217
Allows user to make workspace take up the whole page, covering
the windmill header and footer. Small UI changes to button placement
and workspace size on workspaces page.
- Tested in Chrome 77, Firefox 69, and Safari 13.0.1
- Currently deployed at https://mpingram.planx-pla.net
* 'Make fullscreen' button on Workspaces page allows workspace to
expand to full screen.
* UI change: Increases default size of workspace.
* UI change: Moves 'Terminate Workspace' button to bottom of page,
leaving more space at top of page for workspace.
* UI change: Changes 'Terminate Workspace' button text to 'Cancel'
while workspace is loading.
=> feat(fullpage-workspace): Allow workspace to extend to full-page (PXP-4217)

data/config/default.json, src/Homepage/reduxer.js, src/Index/page.jsx, src/Index/reduxer.jsx, src/Layout/reduxer.js, src/QueryNode/QueryNode.jsx, src/QueryNode/ReduxQueryNode.js, src/Submission/ProjectDashboard.jsx, src/Submission/ProjectSubmission.jsx, src/Submission/ReduxProjectSubmission.js, src/Submission/ReduxSubmissionHeader.js, src/Submission/SubmissionHeader.jsx, src/actions.js, src/components/Introduction.jsx, src/components/layout/TopBar.jsx, src/components/tables/ProjectTable.jsx, src/components/tables/ProjectTable.less, src/components/tables/TransactionLogTable.jsx, src/components/tables/reduxer.js, src/index.jsx, src/localconf.js, src/reducers.js
arborist ui integration--change UI based on user's authz. 
see spec [here](https://docs.google.com/document/d/1IsUlRwoNLUNtT5I9D2tzmepC3y8vdhjmuLfUh-wumvU)
Needs Arborist's GET /auth/mapping endpoint to be exposed via revproxy: 
https://github.com/uc-cdis/arborist/pull/110 
https://github.com/uc-cdis/cloud-automation/pull/1006 
To use this feature, add `"useArboristUI": true` in gitops.json
- get auth mapping from arborist if useArboristUI true in config
- per-project submit data buttons change verbiage based on user's authz
- top bar submit data button changes verbiage based on user's authz
- toggle visibility of recent submissions table based on user's authz
- toggle visibility of map my files card based on user's authz
- toggle form submission and upload file button visibility on …
=> Arborist UI integration

src/components/charts/IndexBarChart/index.jsx
This feels like a hacky solution (why is content spilling into margin?) but seems to be the [recharts-endorsed](http://recharts.org/en-US/guide/getting-started) way to do this (see 3). 
Add right margin (and reduce left) to index-bar-chart to make last x-axis tick (100%) visible.
=> PXP-4445 fix(bar-chart): Add right margin to make last tick visible

src/GuppyDataExplorer/ExplorerFilter/index.jsx, src/GuppyDataExplorer/TierAccessSelector/index.jsx
This PR fullfills https://ctds-planx.atlassian.net/browse/PXP-4310
Deployed in https://qa-brain.planx-pla.net
- Tiered access data explorer now defaults to `Data with Access`
=> PXP-4310 Fix/default access

src/Workspace/Workspace.less, src/Workspace/index.jsx
Commit [3fc783](https://github.com/uc-cdis/data-portal/commit/3fc783d83335d09e1be2c14e8e481855ea0758e9) changed or removed many of classnames depended on by Jenkins integration tests, causing the integration tests to fail. Changing the Jenkins tests themselves is complex due to backwards compatibility requirements (Jenkins tests must still support older versions of the portal), so this commit reverts the classname changes while keeping the fullscreen workspace feature.
Details: The Jenkins @exportToWorkspaceHatchery and @exportToWorkspaceJupyterhub integration tests use classnames of specific elements on the Workspaces page. Specifically, the @exportToWorkspaceHatchery tests expect an element with classname '.workspace' to be on the /workspaces page before a workspace is spawned, and …
=> Fix(jenkins-tests): Revert changes causing workspace tests to fail

README.md
* Added documentation for testing Tiered Access locally by setting the TIER_ACCESS_LEVEL and TIER_ACCESS_LIMIT environment variables.
=> Docs: Add Tiered Access local testing to README

data/config/default.json, src/CoreMetadata/CoreMetadataHeader.jsx, src/CoreMetadata/reduxer.js, src/UserProfile/ReduxUserProfile.js, src/UserProfile/UserProfile.jsx, src/actions.js, src/authMappingUtils.js, src/components/tables/AccessTable.jsx, src/components/tables/AccessTable.less, src/localconf.js
This PR makes the profile page show authz info from fence or arborist or both or neither, depending on the config. Additionally it fixes the file page's download button. See details below. 
For download button, here is why we are throwing out the Fence authz checks: 
1. They appear to have been ad hoc in the first place 
2. They are broken in some cases in commons using centralized auth, whenever fence's userinfo project_access is no longer in sync with Arborist authz (e.g. synapse). 
3. To fall back on the Fence checks if no centralized auth would have required a third new "useArboristAuthz" config var and there was already pushback from the team against more config 
4. We are transitioning to centralized auth anyway
- add config vars showArboristAuthzOnProfile and …
=> Fix/permissions PXP-4524

src/localconf.js
default to showing fence project access on profile if nothing is configured (this is the old behavior) 
related to (amends) (but not in the git sense) https://github.com/uc-cdis/data-portal/pull/610
=> fix(profile-default): default to showing fence project access on profile

package-lock.json, package.json, src/GuppyDataExplorer/ExplorerFilter/index.jsx
https://ctds-planx.atlassian.net/browse/PXP-3968
Bug: Sometimes, the download button in explorer (button type='data') is not disabled when viewing metadata or files the user does not have access to.
Cause: Data from guppy is validated using the 'accessibleValidationField' in the guppy config, but the 'accessibleValidationField' was not always included by default in the data requested from guppy. If the 'accessibleValidationField' was not included, the data validation check that enables/disables the 'data' button would fail and default to 'enabled.'
Fix: Always fetch 'accessibleValidationField' from guppy. This is done by always fetching the fields in 'accessibleFieldCheckList', which includes 'accessibleValidationField'.
Guppy PR for this bugfix: https://github.com/uc-cdis/guppy/pull/66 …
=> Fix(PXP-3968): Fix explorer download button not disabled

src/localconf.js
Fix dumb thing that I did so that windmill will correctly default to showing Fence permissions on profile page but not show them if config.showFenceAuthzOnProfile === false 
🤦‍♂ 
fix bug where Fence permissions incorrectly showed on profile page when config had showFenceAuthzOnProfile set to false
=> fix(profile-default): fix config bug

src/Submission/SubmitTSV.jsx, src/Submission/SubmitTSV.test.jsx, src/Submission/__test__/data.json
Jira: https://ctds-planx.atlassian.net/browse/PXP-3514
Unicode files were handled incorrectly in the 'Upload File' view of the node explorer. This was due to the uploaded files being read using FileReader.readAsBinaryString(), which does not preserve unicode encoding -- this results in non-ascii characters, like 'š', being displayed as each individual byte, like 'Å¡'. Fixed by using FileReader.readAsTextString(). (Also automatically formatted the code.)
Deployed in my dev commons at https://mpingram.planx-pla.net. Steps to test:
0. Create a .tsv file with these contents:
```
type	project_id	submitter_id	acknowledgee	projects.id#1	projects.code#1
acknowledgement	DEV-mpingram-test	Tešt2	Tešt2	d288d790-2019-592e-a067-add692828d09	mpingram-test
```
1. Click on 'Submit Data' in the top navbar …
=> Fix(PXP-3514): Correctly handle unicode file uploads

src/GuppyDataExplorer/ExplorerFilter/index.jsx, src/GuppyDataExplorer/ExplorerTopMessageBanner/ExplorerTopMessageBanner.css, src/GuppyDataExplorer/ExplorerTopMessageBanner/index.jsx, src/GuppyDataExplorer/GuppyDataExplorer.jsx, src/GuppyDataExplorer/TierAccessSelector/index.jsx, src/GuppyDataExplorer/index.jsx
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-4535
A new `hideGetAccessButton` field is added to portal config, in the `dataExplorerConfig` section, the default value is false.
If `hideGetAccessButton` is ture, Get Access buttons is removed from data explorer.
If `hideGetAccessButton` is false and if no `getAccessButtonLink` has been specified in portal config, Get Access buttons is disabled with a tooltip saying “Coming soon“
Deployed in https://mingfei.planx-pla.net/ (with no `getAccessButtonLink` and `hideGetAccessButton` in portal config)
- New `hideGetAccessButton` field to hide the Get Access button in data explorer
- Get Access button in data explorer will be disabled and showing a tooltip if there is no `getAccessButtonLink` in portal config and …
=> PXP-4535 Fix/get access button

src/GuppyDataExplorer/ExplorerFilter/index.jsx
For commons configured to `libre` tier access level, filters should change to `all-data`
- Fixed a bug causing weired filter behaviors in `libre` commons
=> fiix/set filter to all-data for libre commons

src/components/charts/IndexBarChart/IndexBarChart.less
The number in the landing page chart got cut a little bit. There's a CSS offset and I don't know the reason why it was there at the first place. This PR fixes this by removing that offset 
- Fix a UI bug that the landing page chart got cut at the top.
=> fix(offset): remove offset to make chart look better

src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Makes title configurable for Terra Export Warning (https://github.com/uc-cdis/data-portal/pull/642)
- Title in Terra Export Warning is now configurable
- New optional `title` parameter in Terra Export Warning configuration: `terraExportWarning: { subjectThreshold: int, title: string(optional), message: string(optional) }`
=> Make Terra Export Warning title configurable

src/Login/Login.jsx
https://ctds-planx.atlassian.net/browse/PXP-5571
Add a new configurable contact link to the login page, which can be used in place of the contact email. This allows us to specify email links (by using `mailto:email` as the link) as well as normal URLs. This is needed for BDCat as we want to use https://biodatacatalyst.nhlbi.nih.gov/contact as the Login page contact form.
Deployed in https://mpingram.planx-pla.net/login -- try using the contact link.
- Allow use of any link for a contact on the Login page, rather than only emails.
- Added a new property to gitops.json: `components.login.contact_link: { text: string, href: string }`. If `login.contact_link` is present, it will be displayed instead of `login.email`. Email links can be represented in `contact_link` using …
=> (PXP-5571) Allow contact to be a link on login page

src/Layout/reduxer.js, src/components/layout/Footer.jsx, src/components/layout/Footer.less
https://ctds-planx.atlassian.net/browse/PXP-5571
Adds configurable links to the footer of the page. 
Links are specified in the portal config, under `components.footer.links`, which is an array of `{ text: <string, optional>, href: <string> }`.
Deployed in https://mpingram.planx-pla.net/.
- Add configurable footer links to the bottom of the page.
- Added footer link configuration to portal config: `components.footer.links` is an array of `{ text: <string, optional>, href: <string> }`.
=> (PXP-5571) Add footer links

TECHDEBT.md, src/Submission/ProjectSubmission.jsx, src/Submission/SubmitTSV.jsx, src/authMappingUtils.js
Related sheepdog PR https://github.com/uc-cdis/sheepdog/pull/319 
Related commons-users PR https://github.com/uc-cdis/commons-users/pull/810
Fixes submission UI in the program/project submission case. Previously the ArboristUI logic did not differentiate between when a user was submitting program/project nodes and when they were submitting other nodes. CRUD on program/project nodes requires different authz; pre-centralized auth it required `admin: true` in the jwt; post-centralized auth it requires the `services/sheepdog/submission/[program,project]` resources. This PR changes ArboristUI so that it renders the submission UI components ("upload file" button, "use form submission" toggle) on program/project creation only when the user has permissions on the new resources. When ArboristUI is …
=> [PXP-4583] Fix program/project submission UI

README.md, src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Link to Jira: https://ctds-planx.atlassian.net/browse/PXP-5648
Bug: When a cohort with 0 data files is selected in the data explorer, the export to workspace,
export to pfb, and export to Terra buttons were disabled. This PR enables the export to Terra and export to PFB buttons unless a network request for guppy data is in flight.
To test this fix, checkout this branch and run portal locally against BDCat Preprod with: 
```
HOSTNAME=preprod.gen3.biodatacatalyst.nhlbi.nih.gov NODE_ENV=auto bash ./runWebpack.sh
```
Manual test plan:
1. Select a cohort with no data files (in BDC, can do this by selecting ‘no data’ under Subject > Data Type)
2. Export to Workspace button should be greyed out, but Export to Terra Button and Export to PFB Button should be enabled
3. Click Export to Terrra: …
=> (PXP-5648): Enable PFB export buttons when 0 files selected.

data/config/default.json, src/ResourceBrowser/ResourceBrowser.css, src/ResourceBrowser/index.jsx, src/components/layout/NavBar.jsx, src/components/layout/NavBar.less, src/components/layout/NavBarTooltip.css, src/components/layout/NavBarTooltip.jsx
Jira Ticket: COV-98 (OCC Jira)
Allows us to display tooltips on hover instead of (or in addition to 🤷) the usual homepage cards
```
"navigation": {
"items": [
{
"name": "Notebook Browser",
"link": "/resource-browser",
"icon": "query",
"tooltip": "The notebooks pull data from various external sources to generate and output useful tables, charts, graphs, and models."
}
]
}
```
Currently deployed at https://pauline.planx-pla.net
\+ add `tooltip` to the default config, and remove `color` because as far as i can tell it's not used anywhere... let me know if i shouldn't
\+ small fix for a 5px empty space displayed under navbar buttons when the text is a bit long
\+ add padding around the Resource Browser description
- Navigation bar display a tooltip on hover for each button
=> Navbar tooltip on hover

src/components/layout/NavBar.less
My previous change https://github.com/uc-cdis/data-portal/pull/669/commits/e588a0cfab76206c9dfa6e1cda4d2774fa7c2129 fixed a CSS issue but created a new one on mobile screens:
This change is to fix it:
The original change was to fix an annoying extra empty space under the navbar buttons - it turns out we just need to reduce the `.nav-bar__logo` bottom padding, and I need to remove the CSS override in covid19's `gitops.css`
- Fix responsive main menu
=> fix menu responsive CSS

docs/data_availability_tool.md, docs/multi_tab_explorer.md, docs/portal_config.md, src/GuppyDataExplorer/GuppyExplorer.css, src/GuppyDataExplorer/index.jsx, src/localconf.js
This PR fulfills https://occ-data.atlassian.net/browse/COV-78
Allow Guppy Data Explorer to render multiple tabs as configured in the configuration file, each tab will be serving from one ES index
Deployed at https://mingfei.planx-pla.net/explorer
Added new config `explorerConfig` to repleace existing `dataExplorerConfig` and `fileExplorerConfig`
`explorerConfig` is an array which contains multiple configs (one for each explorer tab), e.g.:
``` 
"explorerConfig":[
{                                       ---> 1st tab
"tabTitle": "Data",         ---> optional tab title, if omitted, will default to use the value of guppyConfig.dataType of this tab
"charts": {
"project_id": {
"chartType": "count",
"title": "Projects"
},
...
},
"filters": {
"tabs": [
{
"title": "Case",
"fields": [
"project_id", …
```
=> COV-78 Feat/multi tab explorer

src/Covid19Dashboard/IllinoisMapChart/index.jsx, src/Covid19Dashboard/WorldMapChart/index.jsx, src/Covid19Dashboard/index.jsx
Fixed an error caused by parsing Date incorrectly, which leads to a blank homepage
When creating a Date with no time values, the computed date will be relative to browser's time zone. Which means `new Date("2020-05-10")` will yield `Sat May 09 2020 19:00:00 GMT-0500 (Central Daylight Time)`, in here `2020-05-10` is be treated as a UTC time.
But if a time is giving in date/time pair, the computed date woill NOT do time zone conversion under the table, so `new Date("2020-05-10T00:00:00")` yields `Sun May 10 2020 00:00:00 GMT-0500 (Central Daylight Time)`
Ref: https://www.w3schools.com/js/js_date_formats.asp
https://stackoverflow.com/a/38050824
- Fixed an error caused by parsing Date incorrectly, which leads to a blank homepage
=> fix: use date + time instead of just date

src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx, src/GuppyDataExplorer/configTypeDef.js, src/GuppyDataExplorer/index.jsx
Adds Export to Seven Bridges button to explorer, which allows user to export a PFB to Seven Bridges' analysis platform. This feature is configured with the `export-to-seven-bridges` button type and the `sevenBridgesExportURL` parameter in the portal config. 
- Added Export to Seven Bridges button, allowing user to export a PFB to Seven Bridges.
- Adds new button type `export-to-seven-bridges` to portal config `dataExplorerConfig.buttons.` Example:
```
{
"enabled": true,
"type": "export-to-seven-bridges",
"title": "Export All to Seven Bridges",
"rightIcon": "external-link"
},
``` 
- Adds new parameter `dataExplorerConfig.sevenBridgesExportURL` to portal config, which specifies the URL belonging to Seven Bridges that portal should redirect to. Portal appends the signed url to this URL with …
=> (PXP-5597) Export to Seven Bridges

.babelrc, Dockerfile, package-lock.json, package.json, src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx, src/GuppyDataExplorer/ExplorerVisualization/index.jsx
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-4733
This is the accompanying PR of https://github.com/uc-cdis/guppy/pull/85
Let filters in data explorer support nested fields
To add a nested field to filter, just denote it with a `.`
Example:
>       "filters": {
>         "tabs": [
>           {
>             "title": "Subject",
>             "fields": [
>               "project_id",               --> a regular field
>               "visits.visit_label"      --> a nested field
>             ]
>           }
>         ]
>       },
By default any `.` and/or `_` will be converted to whitespaces and the character immediately after that will be captialized, e.g.: `visits.visit_label` will be displayed as `Visits Visit Label`.
To overwrite, use `fieldMapping`,
Example:
> …
=> PXP-4733 Feat/nested filter

docs/portal_config.md, src/localconf.js
This PR fulfills https://occ-data.atlassian.net/browse/COV-274
Added an optional flag `explorerPublic` in portal config `featureFlags`, e.g.:
>   "featureFlags": {
>     "explorer": true,
>     "explorerPublic": true,
>   }
If set to `true`, the data explorer page would be treated as a public component and can be accessed without login.
Data explorer page would be public accessiable if 1. tiered access level is set to `libre` OR 2. this new `explorerPublic` flag is set to `true`.
Tiered access logics (`libre`, `regular` or `private`) that are set for the env would still apply even if the data explorer page is public.
Backend service should have Guppy 0.4.2+ or 2020.05+ so it can handle user without JWT.
Deployed in https://mingfei.planx-pla.net/
- Added an optional flag `explorerPublic` …
=> COV-274 Public data explorer

src/CoreMetadata/CoreMetadataTable.jsx, src/CoreMetadata/CoreMetadataTable.less
- before:
- after:
remove empty rows + remove table if completely empty + add left padding
- File core metadata table: remove empty rows
=> fix: file core metadata table; remove row when empty

README.md, testSchema.sh
Fix travis failures: Replace dev.planx-pla.net with qa.planx-pla.net because the dev namespace will be shut down every night, while the QA one will not
=> Replace dev.planx-pla.net with qa.planx-pla.net

src/components/layout/NavBar.jsx
- before:
- after:
- Fix navigation bar buttons descriptions when the page is scrolled
=> Fix navbar button descriptions on scroll

src/DataDictionary/highlightHelper.jsx
fix `Cannot read property 'length' of null` error at line 61 `if (cursor < str.length)` 
example https://github.com/uc-cdis/covid19_datadictionary/commit/afb325a2889d2753fe245fd3edc913f7c3de7864#
`null` should not be a value in the dictionary (we're removing it), but the dd viewer should not crash anyway
- Fix issue loading dictionary viewer for null props
=> Fix issue loading dictionary viewer for null props

src/authMappingUtils.js
Fixed a bug cause `submission` page not correctly displaying `Map My Files` component if 1. `useArboristUI` is on AND 2.  service in `file_upload` has been changed from `fence` to `*` (which is intruduced in Indexd 2.12.0 or 2020.07)
Related PR: https://github.com/uc-cdis/indexd/pull/275 (see `Deployment changes`)
- Fixed a bug cause `submission` page not correctly displaying `Map My Files` component
- Portal sould be updated to include this fix if `Indexd` is above `2.12.0` or `2020.07` and user want to use Arborist UI
=> fix: data upload auth check

data/dictionaryHelper.js, src/DataDictionary/NodeCategories/helper.js, src/DataModelGraph/SvgGraph.jsx, src/Explorer/__test__/data.json, src/Explorer/__test__/expected.json, src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx, src/utils.js
Ticket COV-377
- **Current behavior for unknown categories:**
For a category such as `genomic_data_file`, we can "guess" match it with `data_file`, which would result in using the same icon and color for `data_file` and `genomic_data_file`:
- **Dictionary viewer table view:**
- **Dictionary viewer graph view:**
- **Project submission page:**
Alternatively (or in addition to this), we could keep the default icon (or display no icon) and dynamically generate (colorblind-friendly) new colors for new categories, instead of hardcoding which categories are expected and assign colors. I think that would be cool for a future improvement. We can even make it configurable
- Handle icons and colors for new node categories in dictionary viewer and in project submission page by matching them with …
=> Dictionary categories refactoring

src/components/charts/IndexBarChart/index.jsx
@wangfan860 has found a bug that the index bar chart is not displaying accruate data when the numbers are large, see attachments
Turns out portal was doing some unnecessary roundings for the data, fixed in this PR
Suggest to test locally against anvil internal staging
- Fixed a bug causing index bar chart to display inaccurate data due to rounding
=> fix: no rounding

src/Covid19Dashboard/index.jsx
- remove empty forecast plots from county carousel
=> remove forecast images from carousel

src/GuppyDataExplorer/ExplorerTable/index.jsx
Fulfills https://occ-data.atlassian.net/browse/COV-402
- Values in a list is displayed properly by concatenating with `,` in explorer table
=> COV-402 fix: list in table

src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Removes duplicates from the filter of manifest count query
- Removes duplicates from the filter of manifest count query
=> fix: remove dups from filter

Dockerfile
- Update Dockerfile to use Ubuntu base from Quay instead of Docker Hub, due to limits on latter blocking builds
=> Use Quay base image due to Docker Hub limits

docs/portal_config.md, src/Layout/reduxer.js, src/components/layout/TopBar.jsx
Jira Ticket: [PXP-7097](https://ctds-planx.atlassian.net/browse/PXP-7097) 
- Added new dropdown menu to `TopBar` component for handling user profile and logout options, opt-in via config `components.topBar.useProfileDropdown: true`
- At time of writing, `qa-midrc` is only env using the new feature flag. These changes should be deployed alongside each other to production, but nothing will break if done separately.
=> (PXP-7097) Add optional alternate TopBar profile menu

src/CoreMetadata/CoreMetadataHeader.jsx, src/QueryNode/QueryNode.jsx, src/StudyViewer/StudyDetails.jsx, src/Submission/ProjectSubmission.jsx, src/authMappingUtils.js, src/components/tables/ProjectTable.jsx
Portal's Arborist UI feature should check for both `service` and `method`
User should be able to submit data if has `{ service: *, method: *}` for a project
Also wrapped buttons in project submission table with `Link` so user can use right click to open it in a new tab
- Portal's Arborist UI feature should check for both `service` and `method`
- User should be able to submit data if has `{ service: *, method: *}` for a project
- Make buttons in project submission table be able to get right click
=> fix: check user access base on both method and service

src/Covid19Dashboard/PlotChart/index.jsx, src/Covid19Dashboard/README.md, src/components/layout/TopBar.jsx
Jira Ticket: COV-461
- The font size and label length of the COVID19 Dashboard charts is configurable
=> PRC charts truncate labels

src/Index/nctPage.jsx, src/Index/page.jsx
Fixed a bug introduced by https://github.com/uc-cdis/data-portal/pull/742 causing index bar chart to disppear if there is no `homepageChartNodes` but only `boardCounts` and `chartCounts` in portal config
- Fixed a bug causing index bar chart to disappear
=> fix: index bar chart missing if no homepageChartNodes

docs/multi_tab_explorer.md, docs/portal_config.md, src/GuppyDataExplorer/ExplorerFilter/index.jsx, src/GuppyDataExplorer/ExplorerTopMessageBanner/index.jsx, src/GuppyDataExplorer/ExplorerVisualization/index.jsx, src/GuppyDataExplorer/GuppyDataExplorer.jsx, src/GuppyDataExplorer/utils.js, src/GuppyDataExplorer/utils.test.js
Jira Ticket: [PXP-6184](https://ctds-planx.atlassian.net/browse/PXP-6184)
make the nodeCountTitle field optional by using a reformatted dataType if not filled out
Adds a labelToTitle helper function for styling dataType as well as tests for this new function
=> (PXP-6184): refactor/nodeCountTitle: make nodeCountTitle field optional

package-lock.json, package.json, src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Make `format` to be optional in query strings issued by Guppy for backward compatibility, so newer Portal can work with old Guppy if don't need the export to CSV/TSV feature deployed
Companion PR: https://github.com/uc-cdis/guppy/pull/108
Deployed at https://mingfei.planx-pla.net/explorer (Guppy server there is version `2020.12` - old)
Also deployed at https://qa-midrc.planx-pla.net/explorer (Guppy server there is version `0.10.0` - new)
- Make `format` to be optional in query strings issued by Guppy for backward compatibility 
- Guppy to 0.10.1
=> fix: optional format arg

src/Covid19Dashboard/ChartCarousel/ChartCarousel.less, src/Covid19Dashboard/Covid19Dashboard.less, src/Covid19Dashboard/IllinoisMapChart/index.jsx, src/Covid19Dashboard/WorldMapChart/index.jsx
Jira Ticket: [COV-649](https://occ-data.atlassian.net/browse/COV-649)
Change maps to take up 100% height instead of calculating based on window.innerHeight
Removed unneeded related code 
Changed css from grid to flexbox for better flexibility in the layout, constrained main maps width to only show globe once
=> (COV-649): Style/world map view

src/DataDictionary/DataDictionary.css
Jira Ticket: [PXP-6570](https://ctds-planx.atlassian.net/browse/PXP-6570)
- make data dictionary button color will honor the secondary button color
- envs with customized color schemes no longer need to overwrite dictionary button color in their `gitops.css`
=> (PXP-6570): refactor/dictionaryBtnColor: change dictionary btn to use defined global colors

src/index.jsx
React router `Switch` component can only work with 1st level components only https://stackoverflow.com/q/63073469
If put something nested using `<React.Fragment>` under it then it may fail on resolving routes
This shows up in some envs (e.g: bloodpac) as if you navigate to a project page, you only get a header and footer 🤦  
Verify this bug at: https://data.bloodpac.org/Exhale-Fluxion (notice there is no `main-content`)
Deployed and tested: https://qa-bloodpac.planx-pla.net/DEV-test
This fix should be picked into `2021.03` and `2021.04` release 
- Fixed a bug causing page routes cannot be correctly resolved by react router
=> fix: single level router

Dockerfile
Jira Ticket: [PXP-8080](https://ctds-planx.atlassian.net/browse/PXP-8080)
This is basically duplicating what https://github.com/uc-cdis/cloud-automation/pull/1592 is doing
We put it in `cloud-automation` because we don't need to patch each individual portal images then
But we should also ship this with newer portals so if portal is not deployed using cloud-automation will not face this issue
- Disable npm 7 update notifier because it is causing Portal pods to stuck at starting up after 7 days
=> PXP-8080 fix: disable npm update notifier

runWebpack.sh, src/Workspace/Workspace.less, src/Workspace/index.jsx
Jira Ticket: [PXP-7919](https://ctds-planx.atlassian.net/browse/PXP-7919)
Add steps to workspace launching page to visualize progress of spinning up a workspace pod
Require a newer Hatchery, PR: https://github.com/uc-cdis/hatchery/pull/11
Also backward compatiable with older Hatchery (no step progress display)
Deployed and tested in: https://mingfei.planx-pla.net/workspace
- Add steps to workspace launching page to visualize progress of spinning up a workspace pod
=> PXP-7919 Feat/workspace status

src/Analysis/AnalysisJob.js, src/CoreMetadata/CoreMetadataHeader.jsx, src/CoreMetadata/reduxer.js, src/Discovery/Discovery.tsx, src/Discovery/DiscoveryConfig.d.ts, src/Indexing/Indexing.jsx, src/StudyViewer/StudyDetails.jsx, src/UserAgreement/ReduxCertPopup.js, src/actions.js, src/localconf.js, src/localconf.test.js
Jira Ticket: [PXP-8062](https://ctds-planx.atlassian.net/browse/PXP-8062)
Add download object files feature to discovery page
For BPA, this is going to help with replacing the dashboard based publication pages with discovery page
It requires MDS record to contain a special field in a format of an JSON object array, example:
```
[
{
"title": "CNA Data",
"guid": "0a2ea71e-6f43-4588-8703-361cfe67add4",
"description": "fastq files of low pass whole genome sequencing data for copy number alteration (CNA) analysis of FFPE tissue, cfDNA and single cells"
},
...
]
```
And update the discovery page config of the `studyPageFields` component with the following new changes:
```
"downloadLinks": {
"field": "data_download_links",
"name": "Links"
},
```
The list of downloadable files will be displayed …
=> PXP-8062 Feat/disco download

dev.html, docs/portal_config.md, src/components/layout/NavBar.jsx, src/index.ejs, src/index.jsx, src/localconf.js
Jira Tickets: 
[PXP-7991](https://ctds-planx.atlassian.net/browse/PXP-7991)
[PXP-7997](https://ctds-planx.atlassian.net/browse/PXP-7997)
- The data-portal html wrapper's default language is now set to "en". This meets the guideline for default page language in the 508 accessibility specification.
- The alt attribute on the primary homepage logo is now  "[appName] - home" across commons. The Gen3, CTDS logo alt texts are now identical across commons. This meets the guideline for linked image alt text in the 508 accessibility specification.
=> PXP-7997 and PXP-7991

src/Submission/SubmitForm.jsx
Jira Ticket: [PXP-8419](https://ctds-planx.atlassian.net/browse/PXP-8419)
Submission form is crashing when receving input due to trying to asynchronously accessing the property 'target' on a 
released/nullified synthetic event, hence causing page to crash
This is to fix this bug
- Fixed a bug causing submission page to crash when using form submission
=> PXP-8419 fix: input target

src/Workspace/index.jsx
- Use the RStudio logo for both 'RStudio' and 'R Studio' workspaces
=> Use the RStudio logo for both 'RStudio' and 'R Studio'

docs/portal_config.md, src/Discovery/DiscoveryActionBar.tsx, src/Discovery/DiscoveryConfig.d.ts
Jira Ticket: [HP-272](https://ctds-planx.atlassian.net/browse/HP-272)
- Discovery: make `Download Manifest` button name configurable
=> HP-272 Fix/heal btn name

docs/portal_config.md, src/Discovery/Discovery.tsx, src/Discovery/DiscoveryConfig.d.ts, src/Discovery/DiscoveryDetails.tsx, src/Discovery/index.tsx
Jira Ticket: [HP-225](https://ctds-planx.atlassian.net/browse/HP-225)
Added optional config field `dataAvailabilityField` to `discoveryConfig.minimalFieldMapping` to display a `pending` icon for studies that don't have data available yet (but will be in the future)
Logic behind:
```
1. if data_availability is pending, display pending icon
2. else if no authz, display n/a icon
3. else, display lock/unlock icon based on authz and userAuthMapping
```
- Discovery: added `pending` icon for studies that don't have data available yet, requires to set optional config `discoveryConfig.minimalFieldMapping.dataAvailabilityField`
=> HP-225 Feat/new disco icon

src/Workspace/index.jsx
Jira Ticket: [PXP-8431](https://ctds-planx.atlassian.net/browse/PXP-8431)
Workspace launch spinner now supports for waiting for network proxy (Ambassador) becomes ready
When spinning up workspace pods in external cluster, it cannot be accessed via Ambassador until the DNS has been updated
Deployed in https://qureshi.planx-pla.net
- Workspace: add support for waiting for network proxy becomes ready in launch spinner
=> PXP-8431 Feat/ws spin network

src/Indexing/Indexing.jsx
https://ctds-planx.atlassian.net/browse/PXP-8564
The download buttons on the Indexing page have stopped working in Chrome. I'm not sure why, but it seems to have something to do with triggering a click on an `<a>` element AFTER it's been attached to the <body> of the page. Triggering the click BEFORE the <a> element is attached to the body of the page prevents this.
I considered removing the code that attaches the <a> element to the <body> of the page, BUT it's useful as a workaround right now. Because breaking changes in browsers could affect the way that the download buttons work, I think we should keep appending the link to the HTML so that we have an escape hatch if we hit a similar bug in the future.
To replicate:
* Index any file in https://qa-dcp.planx-pla.net/indexing. Expect that …
=> (PXP-8564) Fix for indexing download button not working

src/CoreMetadata/CoreMetadataHeader.jsx
Remove empty values from the header, for example here the file size should not be displayed:
relates to https://github.com/uc-cdis/data-portal/pull/910 and https://ctds-planx.atlassian.net/browse/PXP-8590
- Core metadata / download page: remove empty values from the header
=> Core metadata / download page: remove value if empty

docs/portal_config.md
Reported by user:
> When configuring charts that appear above the table, `explorerConfig->charts->[my_data_field]`. The field must be listed in the `explorerConfig->filters->[fields]`. Apparently, it is the latter that drives the generation of the histogram query that in turn populates the chart. If the field is missing from `explorerConfig->filters` the chart will not render or log an exception in the browser window.
@mfshao:
> the aggs data was generated by filter fields from the beginning. so it is by the design (or it was)
Document that explorer chart fields must be in filters
=> Document chart fields in filters

src/Popup/ReduxWorkspaceShutdownBanner.jsx, src/Popup/ReduxWorkspaceShutdownPopup.jsx, src/Popup/reducers.js, src/Workspace/WorkspaceSessionMonitor.js, src/Workspace/index.jsx, src/covid19Index.jsx, src/ecosystemIndex.jsx, src/index.jsx, src/nctIndex.jsx, src/workspaceIndex.jsx
Jira Ticket: [HP-305](https://ctds-planx.atlassian.net/browse/HP-305)
Add `workspaceShutdownBanner` and `workspaceShutdownPopup` to alert user that their Jupyter notebook's kernel will be or has been shutdown due to inactivity.
The banner will show up when the notebook kernel's remaining life is less than 5 minutes and stays visible until the user take actions to use the workspace, or after the kernel has been killed and the popup will show to inform use that the workspace has been terminated.
The `Close` button on the popup will trigger a call to terminate workspace to Hatchery, in order to clean up any messes remaining.
ℹ️ _Note: some jupyter notebooks (mostly those without using superslim base image) has a feature to automatically refresh the session every 1 minute if the window is …
=> HP-305 Feat/ws kernel shutdown

docs/portal_config.md, src/Discovery/Discovery.css, src/Discovery/Discovery.tsx, src/Discovery/DiscoveryConfig.d.ts, src/Discovery/DiscoveryDropdownTagViewer.tsx, src/Discovery/DiscoveryTagViewer.tsx
Jira Ticket: [HP-555](https://ctds-planx.atlassian.net/browse/HP-555)
Add new "searchable tags panel" to discovery page, replacing the old tags area.
This is an optional UI change and can be turned on by putting the following into portal config `discoveryConfig.features.search` section, see `portal-config.md` for more info
> "tagSearchDropdown": {
>           "enabled": true
>    }
Deployed in: https://qa-heal.planx-pla.net/
- Discovery: new "searchable tags panel" can be enabled via config
- Discovery: tags now are sorted by alphabetic orders
- Discovery: introduced a new config section `discoveryConfig.features.search.tagSearchDropdown`, see `portal-config.md` for more info
=> HP-555 Feat/disco tag dropdown viewer

webpack.config.js
- Fixed a bug causing webpack script to errors out if no `featureFlags` blocks in portal config
=> fix: parse config

docs/study_viewer.md, src/StudyViewer/reduxer.js
This reverts commit eb3fb03ee73425bc6ad672f21b551851ba9ba5ce.
revert #950 - guppy is getting queried over and over again instead of only once when the component mounts, and guppy eventually crashes
=> Revert #950

src/DataDictionary/DataDictionary.jsx
It should be no longer needed to call `.getWrappedInstance()` after updating to Redux 6
- Dictionary: fixed a bug causing `clear history` and `clear result` buttons are malfunctioning
=> fix redux ref

src/Covid19Dashboard/index.jsx, src/StudyViewer/reduxer.js
Jira Ticket: COV-1111
Since https://github.com/uc-cdis/data-portal/pull/967, in the data source the "confirmed" data is in field "C" and the "deaths" data in field "D". The recharts `Line` names were updated so the legend would display "confirmed" and "deaths" instead of "C" and "D". We need to update `renderLocationPopupTooltip` as well to use `dataKey` ("C" and "D") instead of `name` ("confirmed" and "deaths") when fetching values from the data source, or the tooltip only reads undefined data.
- PRC homepage: fix chart tooltips
- Study viewer: log an error when getting a non-200 status code from Requestor and do not process error data
=> Fix PRC chart tooltips and Study viewer API call

src/Covid19Dashboard/IllinoisMapChart/index.jsx, src/Covid19Dashboard/MapSlider/index.jsx, src/Covid19Dashboard/MapSlider/mapSlider.less, src/Covid19Dashboard/index.jsx
~Code is added to add a scroll-down effect to map div when the PRC homepage is loaded. 
MutationObserver is added to the `covid19-dashboard_panel` and it will observe attributes and nodes added to it. Once  `map-slider` has been added as a child to this div, scroll method will be applied~
~Reference for MutationObserver : https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver~
- PRC homepage: date slider style improvements
=> PRC homepage: date slider style improvements

.travis.yml, Dockerfile
Pin npm to 8.5 versions since the new dep resolution logic introduced in npm 8.6 breaks the overrides, need time to investigate
- Pin npm to 8.5 versions
=> pin npm to 8.5.5

src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
When `fileType` is `undefined`, a graphql query is still generated and it fails. The field should be explicitly required.
Relates to https://github.com/uc-cdis/guppy/pull/142
- Catch errors while querying total counts
=> Catch errors while querying total counts

runWebpack.sh
Fix `runWebpack.sh` to be able to run `HOSTNAME=qa.planx-pla.net NODE_ENV=auto bash ./runWebpack.sh`:
```
ERROR: gitops_config - manifest does not exist ../gitops-dev/qa.planx-pla.net/manifest.json
```
=> Fix to run qa.planx-pla.net

src/Analysis/AnalysisApp.jsx
This generic solution allows for any future app to use postMessage to
keep user session alive.
See also https://github.com/uc-cdis/cloud-automation/pull/1927, which uses this feature for Atlas app.
Jira Ticket: [PXP-9641](https://ctds-planx.atlassian.net/browse/PXP-9641)
- New generic event listener to capture messages posted by the app
=> adding a event listener to capture messages posted by the app

src/Analysis/GWASUIApp/CaseControlGWAS.jsx, src/Analysis/GWASUIApp/QuantitativeGWAS.jsx
The short names (e.g., `ASN`) were still being passed to argo wrapper which causes a problem since the CSV will write out the long name. Added even more state vars for the other string. We really should have only 1 state for that whole hare object tbh.
=> fix(hare): pass concept value name

src/Analysis/GWASWizard/GWASCaseControl.jsx, src/Analysis/GWASWizard/GWASQuantitative.jsx, src/Analysis/GWASWizard/shared/CustomDichotomousSelect.jsx
deleting custom dichotomous covariate doesnt delete all of them anymore
*filter was returning empty array each time
=> fix(cd-delete): dont delete all custom dich covariates

src/Discovery/aggMDSUtils.jsx
- Discovery page: fix "undefined tags" error when an entry does not have tags
=> Discovery page: fix "undefined tags" error

src/Analysis/GWASWizard/shared/AttritionTable.stories.jsx, src/Analysis/GWASWizard/shared/AttritionTableRow.jsx
Jira Ticket: [VADC-204](https://ctds-planx.atlassian.net/browse/VADC-204)
- fixes the bug where an attrition row would not always update: when removing a covariate just above another one that is 100% missing, the latter one would get the counts of the previous one (i.e. the counts were not updated)
=> Fix attrition row update

src/Discovery/index.tsx
- Discovery: fixed a bug which causes study with `authz == null` incorrectly showing as `OTHER` accessibility level
=> fix: auth calc

src/Analysis/GWASUIApp/GWASUIApp.css, src/Analysis/GWASUIApp/GWASUIApp.jsx
Jira Ticket: [VADC-213](https://ctds-planx.atlassian.net/browse/VADC-213)
* This makes the whole of the cards on the Gen3 GWAS clickable. 
* It also allows for the user to navigate to them using their keyboard (by pressing the tab key) and trigger them using either the space bar or enter key. Adds a hover state for the cards modeled after hover state used on cards on previous page (App selection UI)
* Include basic ADA accessibility code (tabIndex and aria-labels)
* Removes checkbox interaction
* None
* None
* Addition of hover state and accessibility code
=> Makes whole cards clickable in GWASUIApp.jsx

.travis.yml, Dockerfile, src/Submission/MapDataModel.jsx, src/UserProfile/UserProfile.test.jsx
Related to Jira Ticket: [VADC-59](https://ctds-planx.atlassian.net/browse/VADC-59) , [VADC-247](https://ctds-planx.atlassian.net/browse/VADC-247)
- fixed unhandled promise rejection, which fixes a failing unit test
- fixed failing unit test for UserProfile
- this allows for devs running local node js version > 14 to also get all the tests to pass
- updated node js to 16.x in Dockerfile and Travis CI tests
=> Update node js and fix failing unit tests

src/Analysis/GWASV2/GWASV2.css, src/Analysis/GWASV2/Steps/SelectOutcome/SelectOutcome.jsx
Jira Ticket: [VADC-331](https://ctds-planx.atlassian.net/browse/VADC-331)
This styles the button shown in step 2.0 in the GWAS++ application. The styles are added to GWASV2.css as these styles will be needed in step 3.0 as well. 
Default state is on the left, hover state is on the right:
=> Feat/gwas unified flow step 2.0 styles

docs/portal_config.md, src/Analysis/GWASWizard/wizardEndpoints/cohortMiddlewareApi.js, src/Login/Login.jsx, src/Login/ProtectedContent.jsx, src/Workspace/WorkspaceRefreshToken.js, src/Workspace/index.jsx, src/index.jsx
Jira Ticket: [VADC-154](https://ctds-planx.atlassian.net/browse/VADC-154)
- WTS is a useful service for other backend components that need to access gen3 services using a token bound to a specific user account.
- WTS becomes a dependency for data-portal in general, instead of just for the /workspace subsection of the portal.
- The change IS backwards compatible, since this is controlled by a new optional "feature flag" called `workspaceTokenServiceRefreshTokenAtLogin`. If this is set to `true` it will refresh the WTS token directly at portal login (recommended mode). If not set, this refresh happens only when the user enters the workspace section of the portal (default/old/previous mode).
- this change assumes WTS is already a core/central service. The dependency is hereby moved to the …
=> Centralize WTS refresh token initialization

src/Discovery/index.tsx
* Fixed an Aggregate authz related bug where a `null` response from a key in `wts/aggregate/authz/mapping` is gracefully handled by Data-Portal
=> Gracefully handle null scenario in WTSAuthz

src/Discovery/Discovery.tsx, src/Discovery/DiscoveryActionBar.tsx, src/Discovery/DiscoveryAdvancedSearchPanel.tsx, src/Discovery/DiscoveryConfig.d.ts
Disable filter button if studies are still loading in deiscovery page. This is needed because the filter is using `lodash.memoize()` to create a cache for filter values. If the filter is opened before data loading finishes, there will be no value in the filter and it will not update later.
Demostration of the bug
- Discovery: disable filter button if studies are still loading
- Discovery: filter AND/OR logic toggle button will not be disabled
=> disable filter button if study is loading

src/Analysis/GWASV2/Components/SelectCohort/Utils/CohortDefinitions.jsx
import `queryConfig` from `cohortMiddlewareApi.js` instead of `react-query` for cohort listing.
[VADC-393](https://ctds-planx.atlassian.net/browse/VADC-393)
[VADC-393]: https://ctds-planx.atlassian.net/browse/VADC-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VADC-393: fix query config import

src/Discovery/aggMDSUtils.jsx
* Prevent portal from updating `_unique_id`  to `${commonsName}_${x._unique_id}_${index}` to bring consistency to the id of the studies regardless of their  order in MDS
=> Remove _unique_id from portal logic

data/dictionaryHelper.js, data/getTexts.js, docs/portal_config.md, sanity-check.js, src/Index/nctPage.jsx, src/Index/page.jsx, src/Index/reducers.js, src/Index/utils.js, src/localconf.js
Jira Ticket: [PXP-10565](https://ctds-planx.atlassian.net/browse/PXP-10565) [PXP-177](https://ctds-planx.atlassian.net/browse/PXP-177)
The current chart in homepage will automatically include file node counts in it. This PR add options to opt-out this auto-including feature
- Homepage: added options to exclude File nodes from the charts
- New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them
[PXP-10565]: https://ctds-planx.atlassian.net/browse/PXP-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> PXP-10565/PPS-177 fix: exclude file nodes from chart with options

src/Analysis/GWASV2/Components/AttritionTableWrapper/AttritionTable/AttritionTable.stories.jsx, src/Analysis/GWASV2/Components/AttritionTableWrapper/AttritionTableWrapper.stories.jsx, src/Analysis/GWASV2/Components/AttritionTableWrapper/AttritionTableWrapper.test.jsx, src/Analysis/GWASV2/Components/Covariates/ContinuousCovariates.stories.jsx, src/Analysis/GWASV2/Components/Covariates/Covariates.stories.jsx, src/Analysis/GWASV2/Components/Covariates/CustomDichotomousCovariates.stories.jsx, src/Analysis/GWASV2/Components/Diagrams/CohortsOverlapDiagram/CohortsOverlapDiagram.stories.jsx, src/Analysis/GWASV2/Components/Diagrams/CohortsOverlapDiagram/Simple3SetsEulerDiagram.stories.jsx, src/Analysis/GWASV2/Components/Diagrams/PhenotypeHistogram/PhenotypeHistogram.stories.jsx, src/Analysis/GWASV2/Components/SelectCohort/SelectCohort.stories.jsx, src/Analysis/GWASV2/Components/SelectCohort/SelectCohortDropDown.stories.jsx, src/Analysis/GWASV2/Components/SelectConfiguration/SelectConfiguration.stories.jsx, src/Analysis/GWASV2/Components/SelectHare/SelectHareDropDown.test.jsx, src/Analysis/GWASV2/Steps/ConfigureGWAS/ConfigureGWAS.stories.jsx, src/Analysis/GWASV2/Utils/cohortMiddlewareApi.js
Jira Ticket: [VADC-388](https://ctds-planx.atlassian.net/browse/VADC-388)
- disable retries of failed requests at a global level for the GWAS app. See https://react-query-v3.tanstack.com/guides/query-retries
- align storybook request config w/ real app: for some reason, storybook was using a different config for react-query than the app, leading to confusion and impossible to reproduce/mock scenarios.
- web-service errors are now explicitly catched and thrown. The previous code only worked for errors that happen to not have a json text in them.
[VADC-388]: https://ctds-planx.atlassian.net/browse/VADC-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix/retry request react-query

src/Analysis/GWASV2/Components/SelectCohort/SelectCohortDropDown.jsx
Jira Tickets: [VADC-416](https://ctds-planx.atlassian.net/browse/VADC-416), [VADC-388](https://ctds-planx.atlassian.net/browse/VADC-388) 
- Fixed issue where SelectCohortDropDown would display spinner forever if endpoint failed.
- Fixed bug where SelectCohortDropDown was using the wrong queryConfig, repeating requests 3 times on failure...
[VADC-416]: https://ctds-planx.atlassian.net/browse/VADC-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VADC-388]: https://ctds-planx.atlassian.net/browse/VADC-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix/catch error in SelectCohortDropDown

src/actions.js, testSchema.sh
`fetch()` always returns an `ok` field, it has nothing to do with the arborist API: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful
This was probably confused with the `auth` field in arborist's `/auth/request` endpoint, which should be checked instead of assuming that 200 == authorized. The `/auth/proxy` endpoint behavior is different.
relates to https://github.com/uc-cdis/arborist/pull/155
- Fix misleading use of `fetch()` response `.ok` when calling `/auth/proxy`
=> Fix misleading `/auth/proxy` use

testSchema.sh
Jira Ticket: [VADC-429](https://ctds-planx.atlassian.net/browse/VADC-429)
Removes ref to non-working server in TestSchema.sh
[VADC-429]: https://ctds-planx.atlassian.net/browse/VADC-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(badLineInTestSchemaScript): Remove line 12 per Hara suggestion

src/Analysis/GWASV2/Utils/cohortMiddlewareApi.js
Jira Ticket: [VADC-425](https://ctds-planx.atlassian.net/browse/VADC-425)
-  fix to make sure hare concept id is part of histogram and overlap queries
- also cleaned up some dead code
[VADC-425]: https://ctds-planx.atlassian.net/browse/VADC-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: make sure hare concept id is part of histogram and overlap queries

src/Analysis/GWASV2/Components/Diagrams/CohortsOverlapDiagram/CohortsOverlapDiagram.jsx, src/Analysis/GWASV2/Components/Diagrams/CohortsOverlapDiagram/CohortsOverlapDiagram.test.jsx, src/Analysis/GWASV2/TestData/States/ValidState.js
Jira Ticket: [VADC-290](https://ctds-planx.atlassian.net/browse/VADC-290)
- unit tests for CohortsOverlapDiagram, including mocking of web-services
[VADC-290]: https://ctds-planx.atlassian.net/browse/VADC-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: unit tests for CohortsOverlapDiagram

src/Analysis/GWASV2/Components/Covariates/ContinuousCovariates.stories.jsx, src/Analysis/GWASV2/Components/Covariates/CustomDichotomousCovariates.stories.jsx
Jira Ticket: [VADC-414](https://ctds-planx.atlassian.net/browse/VADC-414)
- Fixed storybook for `CustomDichotomousCovariates` following the component's interface changes in  https://github.com/uc-cdis/data-portal/pull/1204
- Removed unnecessary .css import in `ContinuousCovariates.stories.jsx`
- Added extra storybook scenario for `CustomDichotomousCovariates` to allow for checking the behaviour of the component when a zero overlap selection occurs. 
[VADC-414]: https://ctds-planx.atlassian.net/browse/VADC-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: adjust CustomDichotomousCovariates storybook to component's interface

src/Analysis/GWASResults/GWASJob.jsx, src/Analysis/GWASResults/GWASWorkflowList.stories.jsx
Jira Ticket: [VADC-431](https://ctds-planx.atlassian.net/browse/VADC-431)
* Add `uid` query param to `GWASJob.jsx` endpoints to support archived workflows
[VADC-431]: https://ctds-planx.atlassian.net/browse/VADC-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VADC-431: add uid to argo-wrapper requests

src/Analysis/GWASResultsV2/Views/Home/Home.jsx
Jira Ticket: [VADC-536](https://ctds-planx.atlassian.net/browse/VADC-536)
- Workflows list now always refreshes immediately when VA Results app opens
[VADC-536]: https://ctds-planx.atlassian.net/browse/VADC-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: always refetch workflows list

src/CoreMetadata/CoreMetadataTable.jsx
Data:
```
{
"coverage": ["WI", "IL"],
...
}
```
Before:
After:
- File page: improve display of array values
=> File page: improve display of array values

src/Analysis/GWASResults/Views/Execution/ExecutionTable/ExecutionTable.jsx
Jira Ticket: [VADC-650](https://ctds-planx.atlassian.net/browse/VADC-650)
- GWAS Results app: Run Duration shows correct duration instead of “Invalid date” in Execution view
[VADC-650]: https://ctds-planx.atlassian.net/browse/VADC-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: adjust subtractDates to deal with empty end date

src/Discovery/Discovery.tsx
Missing a space before the resource path:
- Fix the discovery page pop-up text to add spaces where needed
=> Fix discovery page pop-up spaces

package.json
Jira Ticket: [VADC-652](https://ctds-planx.atlassian.net/browse/VADC-652)
Adds ```npm run params``` to npm run storybook and execute before command to start storybook. Tested by git cloning and npm installing a new instance of the application, this prevents the errors: ```ERR_INVALID_ARG_TYPE```, ```Field 'browser' doesn't contain a valid alias configuration``` and others. 
As a result, developers can now git clone the repo for data portal, and run storybook and have it work without needing to run the hostname command
* Updates the storybook npm command so that it works without needing to run additional commands first
[VADC-652]: https://ctds-planx.atlassian.net/browse/VADC-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(storybookCommandUpdate): Updated storybook command

src/Discovery/Discovery.css, src/Discovery/DiscoveryDetails.tsx
Jira Ticket: [HP-1177](https://ctds-planx.atlassian.net/browse/HP-1177)
Deployed in https://qa-heal.planx-pla.net/portal/discovery
- Discovery: `link` and `linkList` typed field now support customize titles for hyperlinks (Note: to have customized titles, each link has to be an object in the format of `{ "link": "http://i.am.a.link.example", "title": "I am a Link Title" }`)
- Discovery: tags and access descriptors can be rendered correctly in tabbed view details page
- Discovery: better styling for fields with no label from config
[HP-1177]: https://ctds-planx.atlassian.net/browse/HP-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HP-1177 fix disco deatils page logic and styling

src/Discovery/DiscoveryActionBar.tsx, src/Discovery/reduxer.js
Jira Ticket: [HP-1266](https://ctds-planx.atlassian.net/browse/HP-1266)
- Discovery: system popups (e.g.: DUA/TOU) will now takes precendes to display over Discovery page popups (file download/export, etc.)
[HP-1266]: https://ctds-planx.atlassian.net/browse/HP-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HP-1266 fix: system popup take precedence over discovery popup

src/Analysis/AnalysisApp.jsx
Jira Ticket: [VADC-788](https://ctds-planx.atlassian.net/browse/VADC-788)
- revert back the GWAS app names so navigation can work again as before (follow-up fix after https://github.com/uc-cdis/data-portal/pull/1446)
[VADC-788]: https://ctds-planx.atlassian.net/browse/VADC-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: revert back the old GWAS app names

src/Workspace/index.jsx
Jira Ticket: [BRH-486](https://ctds-planx.atlassian.net/browse/MIDRC-486)
- Reload Workspace Options when a user selects a different pay model
[BRH-486]: https://ctds-planx.atlassian.net/browse/BRH-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reload workspace options on paymodel change

src/Discovery/DiscoveryDetails/DiscoveryDetails.tsx, src/Discovery/reduxer.js
Jira Ticket: [HP-1298](https://ctds-planx.atlassian.net/browse/HP-1298)
- Discovery: the display of system-level popup (DUA) will take precedence over the Discovery Details drawer
[HP-1298]: https://ctds-planx.atlassian.net/browse/HP-1298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HP-1298 fix: system dua popup take over drawer

package-lock.json, package.json, src/GuppyDataExplorer/ExplorerFilter/index.jsx, src/GuppyDataExplorer/GuppyDataExplorer.jsx, src/actions.js, src/configs.js, webpack.config.js
Jira Ticket: [PPS-588](https://ctds-planx.atlassian.net/browse/PPS-588)
- Fixed a bug about misconfigured webpack publicPath
- Use new Guppy version which supports handling with CSRF tokens
- Ensure CSRF token is passed to Guppy
- Update Guppy to 0.18.0
- After merging this https://github.com/uc-cdis/cloud-automation/pull/2430 any env that is using Guppy and Portal should update their portal deployment to include changes in this PR
[PPS-588]: https://ctds-planx.atlassian.net/browse/PPS-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PPS-588 guppy csrf

src/index.ejs
The previous font didn't support regular weight italic Roboto.  Per @mfshao 's suggestion, now adding.
Tested with https://qa-niaid.planx-pla.net/
- Add support for regular italic Roboto font
=> Update index.ejs for roboto font italic

package-lock.json, package.json, src/ecosystemIndex.jsx, src/index.jsx, src/localconf.js, src/localconf.test.js, src/nctIndex.jsx, src/setupJest.js, src/workspaceIndex.jsx
Jira Ticket: [PXP-11183](https://ctds-planx.atlassian.net/browse/PXP-11183)
- Misc: filter known bot seesion on intake for DD RUM
- Added `crawler-user-agents`
[PXP-11183]: https://ctds-planx.atlassian.net/browse/PXP-11183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXP-11183 feat dd filter bot on intake

src/Discovery/DiscoveryDetails/DiscoveryDetails.tsx
- Discovery: make sure arrays that passed into list components are always single-level
=> fix array handling

src/Analysis/AtlasDataDictionary/AtlasDataDictionaryTable/Components/SearchBar/SearchBar.test.tsx, src/Analysis/AtlasDataDictionary/AtlasDataDictionaryTable/Components/SearchBar/SearchBar.tsx, src/Analysis/AtlasDataDictionary/AtlasDataDictionaryTable/Components/TableRow/NonNumericDetailsTable/NonNumericDetailsTable.tsx, src/Analysis/AtlasDataDictionary/AtlasDataDictionaryTable/Components/TableRow/NumericDetailsTable/NumericDetailsTable.tsx, src/Analysis/AtlasDataDictionary/AtlasDataDictionaryTable/Components/TableRow/TableRow.tsx, src/Analysis/AtlasDataDictionary/AtlasDataDictionaryTable/Utils/ColumnItems.tsx
https://ctds-planx.atlassian.net/browse/VADC-1020
**Developer Notes**
* Debouncing impact on UX is more noticeable when TableData size is larger, such as when the TableData has greater than 8k entries, about 25mb. Adding debouncing reduces excessive rerenders of charts and pauses caused by processing when typing. 
* To test: change line 9 in ```data-portal/src/Analysis/AtlasDataDictionary/AtlasDataDictionaryTable/TestData/GenerateTableData.js``` to ```const numberOfEntries = 8000;``` then run ```Node GenerateTableData.js``` in that directory. Then run storybook with ```npm run storybook``` and use the ```mockedValidData``` selection for the story AtlasDataDictionaryLoading to compare and contrast the UX in this branch vs. master when typing in the …
=> VADC-1020 Feat/debounce vadc data dictionary search

src/Analysis/GWASResults/GWASResultsContainer.jsx, src/Analysis/GWASResults/Views/Home/Home.jsx, src/Analysis/GWASResults/Views/Home/Home.stories.jsx, src/Analysis/GWASResults/Views/Home/Home.test.jsx
https://ctds-planx.atlassian.net/browse/VADC-1134
**Developer Notes**
Before
After 
* Removes the delay  that occurs when opening GWAS Results after switching teams, such as after Selecting team1, Open GWAS Results, wait 5s, Select team2, Open GWAS Results. Before you would see team1 results for first 5s or so
=> bugfix(teamProjectStateManagementRefresh): Initial commit

src/Discovery/Discovery.tsx, src/Discovery/DiscoveryListView.tsx
- Discovery: fix another bug cause the page to crash due to incorrectly handling optional tags field
=> fix missing tag fields in disco table

src/Discovery/DiscoveryActionBar.tsx, src/Discovery/DiscoveryDetails/Components/FieldGrouping/TabField/DataDownloadList/ActionButtons/ActionsButtons.test.tsx, src/Discovery/DiscoveryDetails/Components/FieldGrouping/TabField/Utils/GetMissingRequiredIdentityProviders.ts
- Discovery: fixed a bug that button incorrectly disabled because of duplicated required IDP tags
- Discovery: use file manifest instead of study IDs for direct download
=> use file manifest for batch download

src/Discovery/DiscoveryActionBar/components/DownloadManifestButton.tsx, src/Discovery/DiscoveryActionBar/components/ExportToWorkspaceButton.tsx
Fix this error:
```
Error: DownloadManifestButton(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-794
- Fix an issue with the discovery page not loading when the "download manifest" or "export to workspace" buttons are not enabled
=> MIDRC-794 Fix discovery page when buttons are disabled

src/Analysis/GWASResults/TestData/TableData.js, src/Analysis/GWASResults/Views/Home/Home.stories.jsx, src/Analysis/GWASResults/Views/Home/HomeTable/ActionsDropdown/ActionsDropdown.jsx, src/Analysis/GWASResults/Views/Home/HomeTable/ActionsDropdown/ActionsDropdown.test.jsx, src/Discovery/index.tsx
https://ctds-planx.atlassian.net/browse/VADC-1269
**Dev Notes**
* Functionality can be tested using storybook, i.e. ```npm run storybook```
* Updates test data to make storybook easier to use
* Per discussion with stakeholder, uses AntD notification component instead of AntD Modal. This allows for display of a loading state, a consistent UI with other Action Dropdown events and multiple notifications when retrying multiple workflows simultaneously 
DESIGN
IMPLEMENTATION
* Adds messaging for VADC Results app for workflow limits and prevents submission of retries if workflow limit service is unavailable, returns malformed data or if user's workflow limit is exceeded
=> Feat/results app workflow limit error UI

src/Discovery/Discovery.css, src/components/layout/Footer.jsx
https://ctds-planx.atlassian.net/browse/HP-1687
**Before**
**After**
* Adds media query for Discovery page so buttons are visible in discovery modal (drawer) at screen sizes below 1080px width
=> bugfix(discoveryModalButtonsMediaQueries): Initial commit

package-lock.json, package.json
Link to JIRA ticket if there is one: [PPS-1564](https://ctds-planx.atlassian.net/browse/PPS-1564) [PPS-1567](https://ctds-planx.atlassian.net/browse/PPS-1567) [PPS-1585](https://ctds-planx.atlassian.net/browse/PPS-1585)
- update guppy to 0.19.1
[PPS-1564]: https://ctds-planx.atlassian.net/browse/PPS-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PPS-1567]: https://ctds-planx.atlassian.net/browse/PPS-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PPS-1585]: https://ctds-planx.atlassian.net/browse/PPS-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PPS-1564 PPS-1567 PPS-1585): update guppy to 0.19.1

src/Discovery/DiscoveryDetails/Components/FieldGrouping/TabField/DataDownloadList/ActionButtons/ActionButtons.tsx
https://ctds-planx.atlassian.net/browse/HP-1759
**Dev Notes**
_Before_
State is incorrectly retained for VLMD button after choosing a differet study; a study with VLMD available incorrectly makes other studies show that they have VLMD. 
_After_
State is updated for VLMD button after choosing a different study; one study's VLMD availability does not impact other studies. 
Resets noVariableLevelMetadata when choosing different studies so VLMD button behaves as expected.
=> fix(downloadVLMDButtonReset): Initial commit

src/Analysis/AppCard.jsx
https://ctds-planx.atlassian.net/browse/VADC-1442
**Before**
**After**
Replaces alt text on non-decorative images on analysis app selection page with `alt=""`
=> fix(cardDescriptionParsing): initial commit

docs/portal_config.md, src/Analysis/AnalysisApp.jsx, src/Analysis/AtlasDataDictionary/AtlasDataDictionaryContainer.tsx
Link to JIRA ticket if there is one:  https://ctds-planx.atlassian.net/browse/VADC-1519
- new logic to allow for coexistence of old and new VA data dictionary apps.
Both apps are available under the same /analysis/AtlasDataDictionary location.
- removed unnecessary `ProtectedContent` wrapper for one of the Data dictionary options since /analysis wrapper is already protected (see https://github.com/uc-cdis/data-portal/blob/7d03acf24c498f57748d670773790b834412d3f4/src/index.jsx#L274-L291). 
- new config option `dataDictionaryVersion` that can be set to "new" or something else. If "new", then the new data dictionary component is loaded. This is a temporary solution until we have fully deprecated the old one.
=> Feat: enable old and new data dictionary for VA

docs/portal_config.md, src/localconf.js
https://ctds-planx.atlassian.net/browse/VADC-1430
**Before**
**After**
Using the new key value pair `logoAltText` added from https://github.com/uc-cdis/gitops-qa/pull/3049 this updates the VA logo alt text to explicitly mention it is a logo; the alt text is updated to "A logo and Seal, U.S. Department of Veterans Affairs Data Commons - home" per 508 analysis. If the `logoAltText` doesn't exist, it continues to use the `appName` as before. 
Updates portal config documentation to explain new optional key value pair
=> fix(vaLogoAltText): initial commit

src/Analysis/GWASApp/GWASContainer.jsx, src/Analysis/SharedUtils/AccessibilityUtils/Accessibility.css, src/Discovery/DiscoveryLoadingProgressBar/DiscoveryLoadingProgress.css
Link to JIRA ticket if there is one: [VADC-1479](https://ctds-planx.atlassian.net/browse/VADC-1479)
**Before**
**After**
* VADC-1479: Updated Previous/Next buttons' colors for VA GWAS according to 508 guidelines
[VADC-1479]: https://ctds-planx.atlassian.net/browse/VADC-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VADC-1479: Updated Previous/Next buttons' colors for VA GWAS according to 508

src/Analysis/SharedUtils/AccessibilityUtils/Accessibility.css
Link to JIRA ticket if there is one: [VADC-1420](https://ctds-planx.atlassian.net/browse/VADC-1420)
**Before**
**After**
* If team is not selected, show the disabled button
[VADC-1420]: https://ctds-planx.atlassian.net/browse/VADC-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VADC-1420:Use updated colors only for active button

src/Discovery/index.tsx
- Discovery: fixed a bug causing the discovery page cannot correctly loads metadata in batches if neither AggMDS or StudyRegsistration has been enabled
=> fix discovery batch loading

src/Analysis/SharedUtils/AccessibilityUtils/AccessibilityStyles/Accessibility.less, src/Analysis/SharedUtils/AccessibilityUtils/AccessibilityStyles/AccessibilityGWAS.less, src/Analysis/SharedUtils/AccessibilityUtils/AccessibilityStyles/AccessibilityTeams.less
Link to JIRA ticket if there is one: [VADC-1486](https://ctds-planx.atlassian.net/browse/VADC-1486)
**Before**
**After**
* Fix selected phenotypes/covariates colors
* Restored styles for GWAS and Teams modals
[VADC-1486]: https://ctds-planx.atlassian.net/browse/VADC-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VADC-1486: Fix selected phenotypes/covariates colors according to 508 guidelines

src/Analysis/SharedUtils/TeamProject/TeamProjectHeader/TeamProjectHeader.jsx, src/Analysis/SharedUtils/TeamProject/TeamProjectModal/TeamProjectModal.jsx, src/Analysis/SharedUtils/TeamProject/TeamProjectModal/TeamProjectModal.test.jsx
https://ctds-planx.atlassian.net/browse/VADC-1052
Use Broadcast channel to send message and detect if team project has been updated in another tab. If a change is detected, present modal screen to ask the user to refresh the screen to prevent discrepancy in the current tab being worked on.
=> Show refresh warning when user switch team project in another tab

src/Login/ProtectedContent.jsx, src/Popup/ReduxAuthTimeoutPopup.jsx, src/SessionMonitor/SessionMonitor.test.js, src/SessionMonitor/index.js, src/Workspace/ErrorWorkspacePlaceholder.jsx, src/actions.js, src/components/Popup.jsx, src/covid19Index.jsx, src/ecosystemIndex.jsx, src/index.jsx, src/nctIndex.jsx, src/workspaceIndex.jsx
Link to JIRA ticket if there is one: [VADC-1639](https://ctds-planx.atlassian.net/browse/VADC-1639)
- Refactor logout popup logic to show on all pages except login page 
- Refactor popup to have focus
- add aria-hidden='true' to overlooked error page
[VADC-1639]: https://ctds-planx.atlassian.net/browse/VADC-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (VADC-1639): fix logout not sowing on home page

src/Analysis/GWASApp/Components/AttritionTableWrapper/AttritionTable/AttritionTable.stories.jsx, src/Analysis/GWASApp/Components/AttritionTableWrapper/AttritionTableModal/AttritionTableModal.jsx, src/Analysis/GWASApp/Components/AttritionTableWrapper/AttritionTableWrapper.stories.jsx, src/Analysis/GWASApp/Components/AttritionTableWrapper/ChartIcons/BarChart.jsx, src/Analysis/GWASApp/Components/Covariates/ContinuousCovariates.jsx, src/Analysis/GWASApp/Components/Covariates/ContinuousCovariates.stories.jsx, src/Analysis/GWASApp/Components/Covariates/Covariates.css, src/Analysis/GWASApp/Components/Diagrams/PhenotypeHistogram/PhenotypeHistogram.css, src/Analysis/GWASApp/Components/Diagrams/PhenotypeHistogram/PhenotypeHistogram.jsx, src/Analysis/GWASApp/Components/Diagrams/PhenotypeHistogram/PhenotypeHistogram.stories.jsx, src/Analysis/GWASApp/Utils/cohortMiddlewareApi.js, src/Analysis/SharedUtils/DataViz/Histogram/Histogram.jsx, src/Analysis/SharedUtils/DataViz/Histogram/Histogram.stories.jsx, src/Analysis/SharedUtils/FiltersEnumeration.js
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1635
- add transformation dropdown to histogram and adjust histogram endpoint call to include histogram concept id in variables list instead of being part of the url, according to the backend changes implemented for this same endpoint (see https://github.com/uc-cdis/cohort-middleware/pull/125).
=> Feat: add transformation dropdown to histogram

src/GuppyDataExplorer/ExplorerButtonGroup/index.jsx
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-921
- Explorer page: Do not allow users to click "download manifest" button when the query to ElasticSearch would fail due to having too many terms in the query. Instead, let the user know: "too many rows to download at once; make a smaller selection"
=> MIDRC-921: disable "download manifest" for more terms than the ES limit

data/config/dcf.json, data/config/default.json, docs/portal_config.md, src/Discovery/DiscoveryActionBar/components/DownloadManifestButton.tsx, src/Discovery/DiscoveryActionBar/components/ExportToWorkspaceButton.tsx, src/Discovery/__mocks__/mock_config.json, src/Discovery/index.tsx, src/Submission/SubmissionHeader.jsx
Change link-outs to documentation from legacy documentation at [gen3.org](http://gen3.org/) to new mkdocs documentation at [docs.gen3.org](http://docs.gen3.org/)
=> Update docs links to point to new MkDocs documentation

src/Discovery/DiscoveryDetails/Components/FieldGrouping/TabField/DataDownloadList/DataDownloadList.test.tsx, src/Discovery/DiscoveryDetails/Components/FieldGrouping/TabField/DataDownloadList/DataDownloadList.tsx, src/Discovery/DiscoveryDetails/Components/FieldGrouping/TabField/DataDownloadList/Utils/ProcessData.test.ts, src/Discovery/DiscoveryDetails/Components/FieldGrouping/TabField/DataDownloadList/Utils/ProcessData.ts
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/HP-1977 https://ctds-planx.atlassian.net/browse/HP-1978
Screenshot of the change
Note that the limit of 5 file here is for demo purposes only, the actual limit value is 200
- Discovery: the discovery details page's data download list component will only show the first 200 files in the manifest for direct download, and display a banner if the limit has reached
- Discovery: the discovery details page's data download list component will now sort the entries in the list by their titles
=> HP-1977 HP-1978 Feat/disco file list improve

.github/workflows/integration_tests.yaml, docs/portal_config.md, src/GraphQLEditor/GqlEditor.jsx
- The "Switch to Graph/Flat model" button on the Query page is now displayed when using the `explorerConfig` setting instead of the deprecated `dataExplorerConfig` setting in the data-portal configuration
- The data-portal configuration now describes the `explorerConfig` setting instead of the deprecated `dataExplorerConfig` and `fileExplorerConfig` settings
=> Fix "Switch to Graph/Flat model" button
